### ISSUE TITLE
Support anonymous lookup in LDAP

### ISSUE THREAD

**Issue by khimaros** [authelia/authelia#101]
Rather than binding as an administrative user and doing a lookup, allow binding to LDAP using the user DN that is being authenticated.

**Comment by clems4ever** [comment]
Hello @sllawap, thank you for the proposal. I see two things in your request:
1/ the "administrative" user should be seen as a "lookup" user. Indeed, Authelia needs it because there is no guarantee a given user has the permissions to lookup in a branch of the tree.
2/ However, password reset needs extended (write) permissions, but you're right, the user should be able to reset his own password instead of the "lookup" user.

Can we rename the issue with something more like: "Password reset should be done with user permissions instead of administrative permissions"? Indeed, the current name is a bit misleading because Authelia do support bind mode authentication already.

Thanks,
Clément.

**Comment by sllawap** [comment]
It is possible to configure your LDAP server to allow anonymous bind for reads (ie. to check user presence), this is what I'm referring to. This is essentially ldapsearch -x

**Comment by clems4ever** [comment]
Clear, but you cannot assume anonymous search is allowed on every server either. So, I guess being able to do both would be a good solution to the problem. A proposition could be: if user and password are provided in config then Authelia uses them to do the lookup and if they are not defined, then Authelia could perform anonymous queries. 
What do you think?

**Comment by sllawap** [comment]
Yes, that seems sensible!

As for the bind as user case, this is how Dovecot handles the configuration:

```
auth_bind = yes
auth_bind_userdn = uid=%u,ou=people,dc=zone
```

**Comment by clems4ever** [comment]
Thank you for the example! It's very clear.

**Comment by clems4ever** [comment]
I figured that a user cannot reset its own password because the password reset feature is mainly used when the user lost his password. 

So, eventually the admin user should have the rights to update passwords of users, meaning it MUST exist in configuration. However configuration should allow anonymous lookup as discussed before. To do that, I will add a boolean called **anonymous_lookup** that will be true for anonymous search and false for using the admin user to do the lookup.

@khimaros , what do you think?

**Comment by nightah** [comment]
I think the proposed approach makes the most sense @clems4ever because if permitted the anonymous lookup can and likely would be used and you can track a potential service account for all password resets, making the audit trail much easier to follow.

**Comment by khimaros** [comment]
@clems4ever -- sorry for the delayed reply. Your proposal make sense to me.

**Comment by james-d-elliott** [comment]
I think we can eventually aim to have it setup so users who know their password can change it by adding a UI element in the authenticated page next to logout. 

Combined with #387 this would mean you could do 100% anonymous lookup. The user in question would have to enter 3 passwords, their current one, their desired one, and a confirmation one.

**Comment by james-d-elliott** [comment]
So looking at this now that we have LDAP profile refreshing, it's not actually possible to do this. However we could use a low privileged account that cannot change passwords, and instead use a users account to change the password (i.e. they would need to provide the current one to change it).

**Comment by piotr1212** [comment]
I'd be interested in this feature

**Comment by james-d-elliott** [comment]
@piotr1212 did you get around to testing the build linked in #3291 above?

**Comment by james-d-elliott** [comment]
Or does someone else want to test it?

**Comment by james-d-elliott** [comment]
The *required* config looks like this (i.e. `disable_reset_password` MUST be `false`, `permit_unauthenticated_bind` MUST be `true`, and `password` MUST not be set or must be set to an empty string):

```yaml
authentication_backend:
  disable_reset_password: true
  ldap:
    permit_unauthenticated_bind: true
    password: ""
```
