### ISSUE TITLE
2FA: Duo PreAuth support for full duo flow enabling Multi-Device and Factor selection

### ISSUE THREAD

**Issue by lippl** [authelia/authelia#1039]
Hi, I am currently using my own custom backend app for nginx auth_request implementing ldap auth and more importantly the iframe of [duo web](https://duo.com/docs/duoweb), allowing me to select the device and associated factor I want to use. This is currently the only hold up from switching to authelia, as I have multiple phones and also use the passcodes instead of notifications for example, when not having reception on my phone.

The flow would use the [preauth method](https://duo.com/docs/authapi#/preauth) of the API (also available for the [go implementation](https://github.com/duosecurity/duo_api_golang/blob/master/authapi/authapi.go#L221-L352
)) to retrieve the available devices and factor options and then pass it to the [auth method](https://duo.com/docs/authapi#/auth) after selection by the user. 

If the user is already enrolled, it should be checked if multiple devices are available. If so a slection of them should be displayed. If only one is available, it can be proceeded to the factor selection directly. Then the push can either be sent out directly, or have a selection of available factors be displayed below.
Maybe this should be customizable through a config option to allow disabling the mentioned steps  accordingly.
This might be done in combination to #594 where when the user does not have any devices yet but duo config is available an enrollment option is displayed.

**Comment by clems4ever** [comment]
Hello @lippl , thanks for your feedback. The support of multiple devices is proposed in https://github.com/authelia/authelia/issues/275 and the enrollment is proposed in https://github.com/authelia/authelia/issues/594 as you mentioned. I suggest you follow those threads to keep being updated on the matter. The story makes sense and it's something we definitely would like to have with and without Duo but we are not quite there yet.
Please note that Duo should remain an implementation detail in Authelia, it's not meant to be the only available option so we need to figure out how to smoothly include it and make it compatible with the rest.

Also, given what we have to do in our roadmap (mainly the admin and user interface, OIDC), it's unlikely that we work on Duo specifically soon unfortunately. But if you can join our matrix channel and contribute with code, we can definitely figure out together the best path to let you implement what you need without overlapping with the current roadmap. What do you think?

**Comment by lippl** [comment]
Thanks @clems4ever, that makes totally sense to me!
I am fairly new to golang and react, however I am trying to get up to speed and get involved!

In terms of multi-device in #275 it seems to need DB changes, because of saving data locally, whereas multi-device for duo can be handled via api at "runtime", so it should be much simpler.

**Comment by clems4ever** [comment]
The multi-device feature kind of depends on the user interface that we want to develop in https://github.com/authelia/authelia/issues/303. Because that's the only easy way to let the users manage multiple devices properly (adding, removing, banning). That's why I suggest we discuss with other core contributors about your plans if you have some. However we definitely need to have a way to handle multiple devices and I think introducing the API (without UI) could be a way to move forward with https://github.com/authelia/authelia/issues/303. What do you think @james-d-elliott @nightah?

Regarding your concerns about the DB, today we don't really bind any device directly, I mean we don't store a descriptor of the device, we just store the device handle and/or secret necessary for the device to work (TOTP secret, U2F key handle). So I guess we would indeed need to introduce this notion of device descriptor/id to be able to refer to the device somehow.

**Comment by nightah** [comment]
Given that I utilise Duo I think I have a clear understanding of what you want to achieve here @lippl.

I don't see this as a blocker to #303 or #275, given that the Duo option itself has the ability to expose multiple authentication methods underneath it, the only thing that I would like to see is a clearly fleshed out design for the UX, perhaps even with some mocks and for the option to be well documented (we can help with that).

It's probably worthwhile calling out this might become somewhat redundant when the aforementioned issues are closed off though, primarily because users could just add existing OTP secrets to their account.
The only options provided by Duo that will not be redundant would be the SMS or Call your phone options, though I'm not entirely certain how how much our userbase that could potentially impact.

An alternative could be to look to address multiple device issue and extracting your OTP secret(s) from Duo app instead, but if you're happy to contribute the feature then you're more than welcome to 👍.

**Comment by lippl** [comment]
So I started working on this. You are welcome to take a look [here](https://github.com/lippl/authelia/tree/duo-multi-device).
For the beginning I tried to make the duo api calls more flexible and reusable before starting to implement the multi device feature. Then I decided to focus on multi device first, before going for further methods - as at least the tokens are usable via OTP anyways:
```
- check for device
	- if not provided, do duo preauth
		- if only one device, continue to duo auth
		- if multiple, respond devices back to frontend
	- if provided, use for duo auth
```
So this is the simple design from backend perspective.
I am thinking about a more advanced approach, always running preauth validating DUO API availability and also always validating the device id provided from frontend (as there might be some kind of remember my favorite device or general device storage for users in the future)
```
- do duo preauth
	- if device not provided, 
		- if only one device, continue to duo auth
		- if multiple, respond devices back to frontend
	- if device provided, compare with preauth device list 
		- if found, use for duo auth
		- if not found, let frontend know and send back available devices
```
As I am fairly new to go, I hope my implementation makes sense and aligns with your "design guidelines" or best practices.
I never worked with react before either, so I may need some support or at least guidance here as well... From what I could see from the other interactions between front and backend, they seem to always use single purpose handlers. But when combining this with the shortcut of users who only have one device without selecting with multi-device. So here it would always need two calls and the control would be in the frontend.
```
- request user devices available for push
	- if multiple devices available, promt user to select one
		- request push for selcted device
	- if only one is available, continue directly to 
		- request push for only device
	- if no device available, display error (future enroll)
```
I would rather have used something like an additional response type like maybe a challenge instead of OK/KO to signal this to the frontend or just by its content not only having a redirect but also a device list. So here the control would be in the backend and only require one call for most users.
```
- request push for user
	- if receive OK, display OK and redirect
	- receive KO for error (no device/any error), display error
	- receive OK/Challenge with device list, prompt user for selection
		- request push for specific device
```
Let me know which approach you would prefer in this case. And thankful for every comment :)

**Comment by nightah** [comment]
> I am thinking about a more advanced approach, always running preauth validating DUO API availability and also always validating the device id provided from frontend (as there might be some kind of remember my favorite device or general device storage for users in the future)

We do currently store the preferred 2FA method and the frontend retreives it from the `/api/user/info` endpoint and acts accordingly:

https://github.com/authelia/authelia/blob/697ffd8d73a7cd9a885df73918c38750d5fd4757/web/src/views/LoginPortal/LoginPortal.tsx#L90-L96

At a cursory glance the approach seems sound, I would probably look to extend the user info handler to cater for the additional parameters, perhaps a `HasDuo` bool and then some additional methods to cater for the devices returned from a preauth?
This way you can add the preauth check in the existing WaitGroup:

https://github.com/authelia/authelia/blob/697ffd8d73a7cd9a885df73918c38750d5fd4757/internal/handlers/handler_user_info.go#L16-L80

I suspect this would also mean that for everybody utilising Duo for just push based auth today, on first re-authentication attempt if they have multiple devices that they would get prompted with the proposed challenge.
This then in turn would store their new preferred 2FA method and if they wanted to change the method in future it would be per existing UX of selecting and changing the method while authenticating.

**Comment by clems4ever** [comment]
I was not able to run your branch @lippl , it does not compile but regarding the change to the UI, what do you think about something like the following?

The current screen is like this
![image](https://user-images.githubusercontent.com/3193257/86216563-85021100-bb7e-11ea-9e57-44c38790b50c.png)

We could imagine something like this
![image](https://user-images.githubusercontent.com/3193257/86216608-964b1d80-bb7e-11ea-9678-3002326fdcca.png)

I don't know if that's what you were already doing @lippl , but it could be an idea.

**Comment by lippl** [comment]
Hi, I think I would like to do a more hierarchical flow for setup, where you would click on Push the first time, then preauth runs to query your devices.
If only one is there it will just save it as preferred device and do a push and wait for confirmation - just like now.
If there are multiple use same GUI design as now to list them by their display Name from DUO (made up by device name and number  if available) then the user can select it and will go through same process as with just one. In addition to close button there will also be a new back button then.
![image](https://user-images.githubusercontent.com/9325003/86274565-28c8dc80-bbd2-11ea-8646-4325f56f8dda.png)
So this would be my first phase of implementation. This could easily be reused for multi devices with the other methods. Just not calling duo preauth but rather storage.

In another phase, I can imagine having the same next level in GUI for the methods. So when clicking the device it will list the "capabilities" (methods), if multiple available - data is already available from initial query. When selected it will be used and saved again.
![image](https://user-images.githubusercontent.com/9325003/86275167-26b34d80-bbd3-11ea-8fc6-674a0203765c.png)
It would be a possibility to do devices then in a drop down and display the associated methods then - [just as duo does it themselves](https://guide.duo.com/prompt)
Though, I think it should be rebranded then from Push to duo and have the options in there - as long as DUO config is available.. This way we could also use a second button for authy and [show their capabilities](https://authy.com/blog/quick-and-easy-2fa-adding-authy-to-a-nodejs-app/) in the future, as I think they work quite similar..
![image](https://user-images.githubusercontent.com/9325003/86275110-0d120600-bbd3-11ea-8e3b-ac2f462c9d6a.png)

In an additional phase when no devices or invalid user are retrieved, an [enroll flow](https://guide.duo.com/add-device) could be implemented - and if multiple devices are available it could be linked as either another device called "add/enroll" whatsoever or be a button between close and back.

Those are my thoughts on how this could all work together and be reusable for any other methods, as I think it should not only be a unique characteristic for duo in the long term. However I do not know if this would interfere with your current thoughts on the management center.

**Comment by nightah** [comment]
Your proposal and mocks describe pretty much exactly what I had in mind @lippl, so great clarification there.

I'm probably more in favour of the heirarchical approach as opposed to an inline dropdown. This is only because if a user has multiple devices attached to their account that could look a little odd expanding multiple device capabilities.

Another option could be to go down the device capability expansion approach and when a device is expanded we could collapse all other devices as part of the UX.

Any thoughts as to a preference from your perspective @clems4ever?

**Comment by clems4ever** [comment]
Thank you for the great summary @lippl and the mocks! I'm also in favor of the hierarchical approach because I like it more from the UX point of view. However it's not yet clear to me what happens when the user get passed the 1st factor while she has duo as the preferred method.

What do you think about having the "devices" and "capabilities" views embedded in the push notification view instead of having popups? The thing with popups is that it will be smooth in case the user clicks on "Methods" the first time but will not be so smooth anymore when the Duo is already selected as the preferred method.

By the way, shouldn't devices and capabilities be part of the preferred method somehow?

**Comment by lippl** [comment]
Thanks for the kind feedback!
I updated my branch with a working version of the backend and extended storage for duo device and method. I still need some more harmonization and of course tests for this. I now store the preferred duo device and method, so it can just be used when needed and no preauth needed every time. If no device can be retrieved/or it was deleted from duo account backend will respond with unauthorized. But I would like to prevent this from happening in the frontent.
I did not start with frontend yet, as I have to get familiar with react and your implementation first. However I would like to have the frontend check, whether HasDuo is true before firing duo auth. If it is false I would like to fire the preauth and display the devices (and capabilities) for the user to select. This could all happen without extra pop up but rather in the push notification view. I'll have to play with this a little bit, once I am up to speed :) There it would also be easy to have the select devices button then to restart the selection using preauth.

**Comment by nightah** [comment]
@lippl just pinging you to see if this is something that's still on your agenda, and if you have any questions or need any assistance?

**Comment by lippl** [comment]
Hey, yes it's still on my agenda. But unfortunately since summer I have to take care of some personal matters before I can go back getting my hands on react. Around christmas I should be able to find more time again 👍

**Comment by lippl** [comment]
It did take a while, but I just managed to publish two versions of front and backend in my repo using two different approaches on when to call the preauth API.

[Option 1](https://github.com/lippl/authelia/tree/duo-multi-device)
This was my first try, where the flow is different to what I initially proposed to do, but it seems more like how the rest of the secondfactors is implemented too. Here I decided to not do some auto selection for users the first time if they have only one device (migration scenario). I also implemented both steps with device and method selection even though not having any second method available yet, so you can see how it would work. I added a new Device Selection Container to be mounted within the Push Method. I kept it pretty generic to be able to reuse it for other push providers like Authy or even the other methods already available.

[Option 2](https://github.com/lippl/authelia/tree/duo-multi-device-opt2)
This one uses most of the code and features from option 1 but it also resolves many of the issues I had before. Therefore I needed to rewrite the existing API for the signin Process instead of just extending it. It now does a bit more intelligence in the backend running the preauth first if no device had been selected before or is not valid anymore and is even capable of doing auto selection etc.
For the times possible I also utilize the custom enrollment Url provided by duo if the account policy allows for it. Otherwise I just link to duos start page to be a bit more user friendly.

Open issues are currently, that each selection or go back triggers a new push request as long as the user did not respond to the initial push. So selection requests before authentication triggers redundant requests, where I do not know how to cancel the previous calls after they have fired (or stop their result, as nothing is unmounted at this point). But when selecting after already authenticated everything is fine.

As it is my first go and react implementation I am looking forward for any suggestions and improvements after your review. I am aware I still need to define tests etc. First I wanted to see if it is going a direction you agree with and which version you like better

**Comment by nightah** [comment]
Great job @lippl!

I've got a bit on this weekend but I'll see I can make some time on Sunday to give both of them a try and respond with feedback.

**Comment by nightah** [comment]
So I've had a chance to run both of these, great work so far @lippl!

I like the explicit nature of Option 1 because it allows the end user to follow the flow to set their preferred device and nothing is really assumed.

I love the inclusion of the enrollment Url in Option 2, I do like the ability to pre-auth and auto select a preferred device if only one exists.

A couple things I did notice when attempting these branches:

1. There are no SQL migrations so if a person is utilising an existing storage backend the tables cannot be found and the Duo options outright will not work.
2. When utilising Option 2, after a pre-auth had been attempted and an auto-selection had been made the container doesn't change to present the `A notification has been sent to your smartphone` message along with the mobile image.

Regarding the issue with each selection or go back triggering a new push request, this isn't an trivial problem to solve.
As it seems that you already know, usually we would make that API call in a parent component that isn't unmounted but we don't have that luxury and the other options to resolve this are significant undertakings, I'm thinking React Redux and Redux-Saga.

I think by addressing the issue I've described as 2 that this would still be a workable situation, the other alternative would be to go for Option 2 just remove the auto selection.

**Comment by nightah** [comment]
@lippl I've been thinking about this a little more and perhaps we could use [React Contexts](https://reactjs.org/docs/context.html) to achieve what we need for Option 2.

What I'm thinking is perhaps a bool and string/time field that's passed in the context.
Bool is set to false initially and the other field is used to capture the current browser time.

Before a push request is made we should check to see the value of the bool, if false proceed, otherwise if true additional logic with browser time detailed below to follow.

When we hit the push request the bool within the Context is set to true and current browser time is captured, if the flow isn't interrupted (completed successfully) eventually the bool is set back to false when the user has been authenticated at the end of the flow.

If the flow is interrupted (back in the browser) then before the push request is made a caculate the time diff between stored browser time + 60 secs (or whatever the timeout is for a Duo request to be responded to) and then we can reset the bool back to false.

This also has the advantage of not sending out requests during each selection until either the first one has been completed successfully or timed out (successful flow) or after the defined timeout has been reached for an interrupted flow.

**Comment by james-d-elliott** [comment]
This sounds like a sensible approach to me.

**Comment by lippl** [comment]
@nightah thanks for the review and input - much appreciated!

@james-d-elliott I am not too sure on how the Storage Schema Versioning Model is working though. Do all tables/indexes need to be mentioned in the `sqlUpgradeCreateTableStatements`/`sqlUpgradesCreateTableIndexesStatements` per version again or should I only add the new ones/skip the latter if no new indexes are needed?
If I read it correctly, the schema is always built one version after the other for new installations as well as upgrades.
`upgradeCreateTableStatements` on the other hand checks for the table names so only additional ones are added, or ist this only to double check?
In my current understanding I would create a `upgradeSchemaToVersion002` function and only add new tables to the schema versioning and inidices could be skipped!?
Also it doesn't (yet) check for alterations in the statements like new columns, does it?

I was thinking about Contexts as well but didn't want to change too much on the upper levels to begin with, but I guess I will give it a try if there is no other option then.

Once I sorted things out, decided for an option and have it running I will do the PR then.

**Comment by clems4ever** [comment]
> @lippl I've been thinking about this a little more and perhaps we could use [React Contexts](https://reactjs.org/docs/context.html) to achieve what we need for Option 2.
> 
> What I'm thinking is perhaps a bool and string/time field that's passed in the context.
> Bool is set to false initially and the other field is used to capture the current browser time.
> 
> Before a push request is made we should check to see the value of the bool, if false proceed, otherwise if true additional logic with browser time detailed below to follow.
> 
> When we hit the push request the bool within the Context is set to true and current browser time is captured, if the flow isn't interrupted (completed successfully) eventually the bool is set back to false when the user has been authenticated at the end of the flow.
> 
> If the flow is interrupted (back in the browser) then before the push request is made a caculate the time diff between stored browser time + 60 secs (or whatever the timeout is for a Duo request to be responded to) and then we can reset the bool back to false.
> 
> This also has the advantage of not sending out requests during each selection until either the first one has been completed successfully or timed out (successful flow) or after the defined timeout has been reached for an interrupted flow.

To answer your question @nightah , we don't really need a Context. A hook is sufficient given it is instantiated high enough in the hierarchy of components. Contexts are usually used in case one wants to diffuse a variable throughout the tree of components without the pain of passing it through all of the components. It makes sense for themes for instance but probably not so much for the use case you mention in my opinion since it's very local.
