### ISSUE TITLE
Discussion:  Reconfigure docker deployment to make simpler.

### ISSUE THREAD

**Issue by CHBMB** [authelia/authelia#1097]
Further to a comment I made in the Matrix room.

Both @aptalca and I wondered if there's a couple of ways docker deployment might be made a little easier. 

1. Get the user to map only `/etc/authelia` to a volume or folder on the host. 
2. If `configuration.yml` doesn't exist in `/etc/authelia` copy the sample one to the directory so it's available on the host for the user to start configuring.

If you then extrapolate this further and also by default configure any other files the user might be using, such as `db.sqlite3` and `users_database.yml` are also by default configured to be in `/etc/authelia` it vastly reduces the complexity of mapping these volumes/files.

`users_database.yml.sample` could also be copied across from the image to `/etc/authelia` if `users_database.yml` doesn't exist.

It shouldn't affect existing users who already have configured their `configuration.yml` and file paths and we think it might avoid a lot of the simpler issues arising with a docker deployment by giving authelia a single location on the host for user configurable files & persistent data.

The relevant parts of `configuration.yml` that would be affected are:

```
# log_file_path: /var/log/authelia
```
```
  # file:
  #   path: ./users_database.yml
  #   password:
  #     algorithm: argon2id
  #     iterations: 1
  #     key_length: 32
  #     salt_length: 16
  #     memory: 1024
  #     parallelism: 8
```
```
storage:
  # The directory where the DB files will be saved
  ## local:
  ##   path: /var/lib/authelia/db.sqlite3
```
```
notifier:
 # You can disable the notifier startup check by setting this to true.
 disable_startup_check: false

 # For testing purpose, notifications can be sent in a file
 ## filesystem:
 ##   filename: /tmp/authelia/notification.txt
```

The resulting docker compose would be
```
version: "2.1"
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - <path to config folder on host>:/etc/authelia/
    ports:
      - 9091:9091
    restart: unless-stopped
```
And for docker itself
```
docker run -d \
--name=authelia \
--net=docker \
-p 9091:9091/tcp \
-v <path to config folder on host>:/etc/authelia/ \
authelia/authelia
```

As I've said, I'm already up and running (thanks to the help earlier :wink: ) but this may prove useful for new users in terms of making things easier with less potential for errors.

Posted here at the request of @clems4ever for discussion amongst you all.

Thanks again for this wonderful piece of work, I love it!

**Comment by clems4ever** [comment]
Thanks @CHBMB for reporting this suggestion.

So for me there are two distinct items in this request:
1. Copy sample files where they should be located to ease deployment.
2. Merge all files (config and data) into one directory to mount one single volume instead of two.


So let's discuss the points independently.
1. I  agree with the suggestion and I see it as an opportunity to simplify the setup instead of digging into the doc or the github to bootstrap an instance.

2. I actually searched a bit to find how other famous images do and the big ones usually have two separate volumes for config and data (https://hub.docker.com/_/postgres, https://hub.docker.com/_/mariadb, https://grafana.com/docs/grafana/latest/installation/docker/, https://hub.docker.com/r/prom/prometheus/tags) and one counter example (https://hub.docker.com/_/nextcloud). This does not mean it's the best way to do but imo it's done like that because it's how system admins are used to configure their systems.
Moreover, I'm not really sure it will actually ease the setup in any way. Indeed, some users faced issues with their config but I think it's not because of the volume mappings themselves but rather the paths inside the volumes. So having one volume instead of two would not have solved it anyway. I'll let my teammates give their opinion on that one but maybe we should consider actual issues before considering moving to something that is a less standard for system administrators.

What do you think @nightah and @james-d-elliott ?

**Comment by CHBMB** [comment]
@clems4ever Yeah, I understand, a lot of the file system structure is historical and I do get that.  Like I said, it's just a suggestion.

An alternative would be to have two subfolders with a common parent.  Again, it would deviate from convention.

This is your baby, you guys got to do as you see fit. :+1:

**Comment by nightah** [comment]
So regarding the first point I'm totally on board, I'm a big fan of the single config volume ala the LSIO containers unless there's an explicit reason to split volumes.

For our specific use case I can't see any real technical pros or cons to changing this behaviour. Most of our examples mount the directory structure from the same location on the host, so this would be a step towards simplification and as such I think is an easy win.

The second point also would lend itself to simplification, as discussed above to require less manual intervention for bootstrapping the environment. I see two ways to do this:

1. Create an entrypoint shell script that will check if the files exist, if not copy them over based on the sample files.
2. Build some logic into the Go binary which will generate the config file based on the samples and also notify the user when doing so.

The latter I think brings some more benefits because it can be useful in more deployment methods than just the Docker one. It also means we wouldn't provide a "configuration file not found" type error because we will generate one if that is the case.

This same logic could be applied to the user database if a file backend is configured.

In the case of the storage backend, where sqlite is selected, this isn't really an issue because this file will be generated on first run to whatever location that is configured.

To generate the file from the Go binary in Docker this is how I envisage the workflow:

1. User runs Authelia container for the first time, default parameters are specified `/etc/authelia/configuration.yml` and no config file is present.
2. The Authelia binary generates `/etc/authelia/configuration.yml` logs an informational message and exits with os.Exit.
3. Docker would restart the container and load the generated configuration file.

The user can then go away and modify the configuration as necessary and restart the container.

**Comment by clems4ever** [comment]
Fair enough, it was more of a tiny concern because it's not very clear to me how having one volume instead of two would help users. I guess it's more of a subjective topic but I'm ok with a single volume if I'm the only one challenging it. It's no big deal because it's just a documentation thing anyway. Someone willing to split the old way (as it's done by package manager) could still do it.

Regarding the second item, I'd rather do it within the Go binary as you suggest @nightah , it indeed propagates to all deployment methods (Docker image and build from source). 

Though, I don't get
> 3. Docker would restart the container and load the generated configuration file.

Why would docker restart the container without human intervention?

**Comment by clems4ever** [comment]
Fair enough, it was more of a tiny concern because it's not very clear to me how having one volume instead of two would help users. I guess it's more of a subjective topic but I'm ok with a single volume if I'm the only one challenging it. It's no big deal because it's just a documentation thing anyway. Someone willing to split the old way (as it's done by package manager) could still do it.

Regarding the second item, I'd rather do it within the Go binary as you suggest @nightah , it indeed propagates to all deployment methods (Docker image and build from source). 

Though, I don't get
> 3. Docker would restart the container and load the generated configuration file.

Why would docker restart the container without human intervention?

**Comment by nightah** [comment]
> it's not very clear to me how having one volume instead of two would help users

We may not see a direct correlation here, but I’m of the opinion that if we mount a single volume/directory and our examples also support this that there’s less opportunity for someone that’s adapting our samples to run into issues. Like you said it’s subjective though.

> Why would docker restart the container without human intervention?

It technically wouldn’t, but our examples have a restart policy defined so that’s what would be triggering the container restart.

@james-d-elliott keen to hear your thoughts/opinion on the topic.

**Comment by clems4ever** [comment]
> It technically wouldn’t, but our examples have a restart policy defined so that’s what would be triggering the container restart.

Oh ok, makes sense.
