### ISSUE TITLE
Add SQRL support

### ISSUE THREAD

**Issue by achrjulien** [authelia/authelia#1126]
Is there any plans to support SQRL authentication?

SQRL (pronounced "squirrel")[3] or Secure, Quick, Reliable Login (formerly Secure QR Login) is a draft open standard for secure website login and authentication. The software typically uses a link of the scheme sqrl:// or optionally a QR code, where a user identifies via a pseudonymous zero-knowledge proof rather than providing a user ID and password. This method is thought to be impervious to a brute force password attack or data breach. It shifts the burden of security away from the party requesting the authentication and closer to the operating system implementation of what is possible on the hardware, as well as to the user. SQRL was proposed by Steve Gibson of Gibson Research Corporation in October 2013 as a way to simplify the process of authentication without the risk of revelation of information about the transaction to a third party.

from https://en.wikipedia.org/wiki/SQRL

For understanding the protocol, please watch: https://www.youtube.com/watch?v=GrB6pcbXek8

More information: https://www.grc.com/sqrl/sqrl.htm

**Comment by clems4ever** [comment]
Hello @achrjulien , I had a look at the video you linked, it greatly explains how SQRL works under the hood, I liked it. The concept seems pretty good. It's a smart way to combine some crypto algorithms together to remove the multiplication of passwords as described in the Wiki page. With SQRL, there is only one password required to allow the authentication process. The re-keying feature is also smart.

I've never heard about SQRL before now so I'm grateful you opened it. Now, if we look at the authentication landscape I think the technology closest to SQRL I can think of is WebAuthn. Btw there seems to be many heated discussions around the differences as we can see in:
- https://sqrl.grc.com/threads/differences-between-sqrl-and-webauthn.909/
- https://security.stackexchange.com/questions/43374/could-sqrl-really-be-as-secure-as-they-say

I think theoretically the security model of SQRL is good, not perfect as any other models (even WebAuthn) but definitely better than using passwords and better than client certificates from a UX perspective because they are just a pain to manage and install by users.

However, for the time being, if I had to choose between WebAuthn and SQRL, I'd go for WebAuthn and here is why. Even though both seem similar in the sense that they are using asymmetric crypto to authenticate users pseudo anonymously to websites with the smoothest user experience, I see three things that makes me choose WebAuthn over SQRL:

1. WebAuthn is newer but there seems to be more traction around it since many big tech companies are behind it and many browsers already integrated it as we can see from https://caniuse.com/#search=webauthn.
2. The protection against phishing brought by WebAuthn is definitely something of high value. There seems to be some design around it on the SQRL side so it's not so advanced.
3. WebAuthn aims to remove passwords entirely (while there is still one in SQRL) by relying on an enclave and identity assertion based on something you own and/or are.

So I don't close the door to implementing SQRL in the future if it gets more adoption and traction but for now I'd focus on WebAuthn. Also, I stay optimistic about SQRL because apparently W3C is interested by the project so there are chances that we end up with a mix of both worlds eventually. We'll see!

What's your current usage of SQRL @achrjulien? Do you use some applications already supporting it? What's your experience with it?

**Comment by clems4ever** [comment]
I'm closing this issue since it's not actionable for the time being.
