### ISSUE TITLE
Support custom theme in the client

### ISSUE THREAD

**Issue by n4kre** [authelia/authelia#113]
Hi,

it would be quite a nice enhancement to be able to configure Authelia so that specific icons, title, text, email template, etc. are used instead of the default ones.

**Comment by clems4ever** [comment]
Hello @n4kre , it would be great, indeed! Clearly a nice to have.

**Comment by 726a67** [comment]
It would be great (in my opinion) if this feature was implemented dynamically (perhaps per configuration file parameter) so that users utilizing pre-built instances of Authelia (e.g. docker) could make use of the feature at runtime in a turnkey way.

**Comment by nightah** [comment]
@BankaiNoJutsu given your previous contribution in respect to this,  is this something you might have the desire and bandwidth to look at 😄?

**Comment by BankaiNoJutsu** [comment]
@nightah I may yes. I had some dev for dynamic theming going, but this was for the v3. I still had no time to test nor adapt to v4 yet. But it's definitely in my pipe of want to do. I just cannot give any ETA sorry.

The main issue I had was that the scss etc need to be compiled before run, therefore it adds some complexity in order to really get it dynamically. In the past there was therefore a need to re-build to change the theme, which is not satisfying enough for me ;)

I got to the point of being apple to apply a theme per JS, but of course it would get reverted on page load.

Lastly, i believe the project should remain small and light, and having multiple themes to store and maintain may get against this rule i setup to myself.

I will update this post when i get some time to get back to it :)

**Comment by nightah** [comment]
@clems4ever might be able to provide some context since the frontend was re-written using MUI.

> Lastly, i believe the project should remain small and light, and having multiple themes to store and maintain may get against this rule i setup to myself.

We've made a lot of ground here since the re-write of the backend in Go, we're almost a third of our original size from v4 -> v3 so I don't particularly think a couple themes will affect us too much in this regard.
However, I completely understand where you're coming from and agree that we should do whatever we can to alleviate the concern.

**Comment by 726a67** [comment]
@nightah I think the inclusion of a 'themes' folder (wherein the user could drop their own images/css/etc) could help alleviate concerns regarding size. I certainly understand (and agree with) the desire to keep Authelia as lightweight and maintainable as possible.

**Comment by 726a67** [comment]
Any updates on this issue?

**Comment by BankaiNoJutsu** [comment]
> Any updates on this feature request?

Yep, i started working on this.

**Comment by 726a67** [comment]
I think the user management interface (#974) is going to be under development for some time, so it may make sense to implement this in an iterative fashion: first as a boot parameter, and maybe later as a function of the management interface.

**Comment by BankaiNoJutsu** [comment]
@726a67 i have a working prototype, need to finish, cleanup and is good to go!

**Comment by 726a67** [comment]
@BankaiNoJutsu any news to share? I was following your progress via riot/matrix, but I haven't seen a new PR since your old one was closed out.

**Comment by BankaiNoJutsu** [comment]
I haven't had time to work on it more. It's just a matter of creating a new
branch on my side and recreating a PR tho.

**Comment by 726a67** [comment]
No worries; thanks for the update and the good work!

**Comment by adyah-cisco** [comment]
@clems4ever or @BankaiNoJutsu Is there any files we can override with a custom Dockerfile for now to achieve the same? Are all the images stored in some path with file names that are loaded?

**Comment by nightah** [comment]
@BankaiNoJutsu do you have the opportunity to close this issue off?
If not are you okay for me to pick up your PR and finish it off?

**Comment by BankaiNoJutsu** [comment]
Sadly no time, military service :(

Amir, feel free to pick up!

Le dim. 3 janv. 2021 à 14:59, Amir Zarrinkafsh <notifications@github.com> a
écrit :

**Comment by nightah** [comment]
No problems at all, thanks again for all your effort through the rewrites and getting as much as you had completed.

I've got a PR up waiting to be reviewed and accepted.

Thanks to everything you had done beforehand it was only a little work on my side to polish it up and finish!

**Comment by gene1wood** [comment]
So PR #1584 Adds theme support but explicitly doesn't add theme support. @nightah Should this issue be-reopened since #1584 doesn't actually address it?

**Comment by trieded** [comment]
Hoping to have custom theme support as well

**Comment by small-grey-dog** [comment]
Would also love the ability to customize the theme

**Comment by StephanRichter** [comment]
+1 for custom themes or at least the option to add a custom css

**Comment by BankaiNoJutsu** [comment]
I'll have a look at this soon
