### ISSUE TITLE
Add option to not refer to non-free TOTP clients

### ISSUE THREAD

**Issue by vdot0x23** [authelia/authelia#1145]
I propose an option to disable references entirely and an option to refer to free software like [andOTP](https://f-droid.org/en/packages/org.shadowice.flocke.andotp/) or [FreeOTP+](https://f-droid.org/en/packages/org.liberty.android.freeotpplus/), both are available on F-Droid.

**Comment by clems4ever** [comment]
What I propose is rather add a link to a dedicated page in the documentation listing all possible alternatives. That would avoid adding a customization just for that. What do you think?

**Comment by james-d-elliott** [comment]
Seems like a sensible approach. We could account for many different environments:

Mobile (Android, F-Droid, iOS, etc)
Non-mobile (Linux, Windows, OSX)

**Comment by vdot0x23** [comment]
If that link is configurable I agree that it is sensible.
If not, I don't like the idea of depending on an external website (authelia.com in this case) :)

**Comment by clems4ever** [comment]
Ok why not. It should be easy enough to add the URL to the configuration and get it displayed.

**Comment by mlavi** [comment]
Would you like a draft page for OTP solutions? I could contribute raw material here or submit markdown as a PR?

**Comment by nightah** [comment]
Happy for you to add a page in the docs for this.

We can look to include the ability to specify a link in the configuration which will propagate accordingly when we've got the docs with the alternatives in place.

**Comment by mlavi** [comment]
@nightah Here's my blog entry: https://mlavi.github.io/post/dynamic-passwords-topt/ and the markdown source is https://github.com/mlavi/hugo/blob/master/content/post/dynamic-passwords-topt.md

What I can do now is expand on the alternatives instead of just pointing to some lists and the justification for it. Sorry it took a while, but it was a pretty exhaustive writing excursion to get to this point and I just published on my blog.

Please let me know your thoughts for an excerpt, expansion, next steps, etc.

**Comment by james-d-elliott** [comment]
Closing in favor of #1981, we should implement both of these features as one.
