### ISSUE TITLE
Add option to store MFA token and preferred method in LDAP

### ISSUE THREAD

**Issue by koshatul** [authelia/authelia#1147]
This would be to have a deployment between full and lite for securing multiple remote sites using the same LDAP backend but their own local storage (MySQL, etc).

So you could have `us.example.com`, `ca.example.com` and `eu.example.com` all using a central LDAP service, but local storage for authentication attempts and token temporary storage.

This also means that MFA tokens could be setup centrally and only have read access in each of the sites.

I've got a [branch](https://github.com/koshatul/authelia/tree/ldap-mfa) I'm working on to implement it, but before I submit a PR any advice would be appreciated.

**Comment by clems4ever** [comment]
Hello @koshatul , Thanks for reporting this and having worked on it!
I understand the requirement of multi region setup to optimize the latency of most of the operations. Great job with the implementation, it's cool if it works for you so far.

However, I think we should consider the solution differently. Because storing those secrets in the AD will surely help you in the short term but not so much for the long term as we'll likely add more information about the device handles or secrets, like a name, a creation date, a revocation date, a revocation interval to be able to manage them from the upcoming user&admin  interface. It will be hard to store all that data in AD or LDAP server and I think we also want to keep all this information together as much as possible to avoid desync issues between the components.

Would not replicating the LDAP server in all regions an option for you?

If not, I think finding how to make Authelia work in a multi availability zones setup is a good initiative but it definitely needs thinking and design imo.

The first thing that comes to my mind is that the storage backend should handle the replication in order for Authelia to remain as simple as possible. Remember Authelia is a security component, we should strive toward the least code possible because the least code the better to avoid bugs and therefore potential security breaches. However, if the backend definitely cannot handle it, which might happen (at least with non enterprise versions usually) then we need to design something with a high-level view to be sure it does not go against the roadmap, it's natural to users configuring it and we don't miss something.

We can create a dedicated matrix room and chat about that with other contributors if you want and if it's the only way for your to move forward @koshatul.

**Comment by nightah** [comment]
@koshatul could you please clarify the actual issue you’re trying to solve here?

Please correct me if I’m wrong but based on your post if I’ve understood correct, you already have a centralised/replicated LDAP.

Is there something specific stopping you from replicating your storage backend?

I think the middle ground deployment you are proposing would be with LDAP, Replicated SQL and localised Redis instance for each region. So your active sessions aren’t replicated to all sites but presumably the local redis instance to that location handles this.

So in terms of component to storage mapping it looks like this:

Users and Groups -> File or LDAP
Authentication tokens and user preferences -> SQL (MariaDB, MySQL, PostgreSQL, SQLite)
Session storage -> Redis (instance or cluster) or in memory.

**Comment by koshatul** [comment]
Mainly the economy of adding another service that needs to be maintained and secured, LDAP is already replicated and part of the maintenance schedule.

LDAP is already replicated (OpenLDAP, not AD) but it isn't economical to add additional replicated SQL for just for MFA, and having a localised MFA isn't great for usability.

Storing the MFA is LDAP would solve that.

Sessions don't need to be replicated, outside of our use case even signup tokens don't need to be replicated, if you're storing the MFA secrets in LDAP then if you setup the token at site1, getting an email and a link to site1 to complete setting it up would make sense and site2/siteX not knowing that token wouldn't be break the usability.

I didn't like in my implementation that I'm embedding the local/sql providers in the LDAP storage provider to provide the additional bits of the `storage.Provider` interface that aren't logical to store in LDAP (`*IdentityVerificationToken` and `*AuthenticationLog`).

If changing the storage is on the roadmap, maybe separating out those functions into different providers would be logical.

I'm on the fence about authentication attempts being LDAP, there's already some precedent in the OpenLDAP password policy schema with `pwdFailureTime` and `pwdHistory` attributes (storing previous passwords or the last time an authentication failed), but personally I feel that LDAP is something that changes infrequently and replication is considered quick but not immediate.

**Comment by nightah** [comment]
I understand better now, thanks for the clarification @koshatul.

While given the circumstances and your specific use case this change seems to make perfect sense, I'm having a hard time like @clems4ever attempting to figure out how this would fit down the line.

Just to give you some background around our position and my thought process.

I feel there's 3 typical user profiles regarding usage of the "user backend" element for people that utilise Authelia as a service today.
1. A home enthusiast that wants something simple and quick and they typically are fine with the file based backend
2. A home enthusiast that wants to go a step further and ensure there's a certain level of resilience/redundancy in the solution (this is usually where lots of people get tripped up working through the LDAP learning curve if they have had no prior experience)
3. An enterprise (small, medium or large) who already have a LDAP footprint, be it one of the open source variants or MSAD

I personally fell into profile 2 when I first stumbled upon the project early on in the development.

During those days when looking to introduce new features like the network based authentication bypassing we attempted to utilise LDAP as our source of truth. So we modified the schema and introduced an attribute to store IP addresses or subnets that would tie an address to a user. This quickly fell flat on it's face because it slowly came to light that;
1. Making changes to LDAP schemas to store non-RFC conformant data isn't easy for most people and actually could become a significant source of pain for support/troubleshooting
2. LDAP while great for all of the things it can do wasn't really extensible enough given our future plans for Authelia

With the prevalence of OAuth, SAML, OIDC and other emerging technologies/standards our vision and approach is to make our best efforts to slowly move all configuration for Authelia into the SQL backends.
This is looking primarily to leverage the widespread knowledge of deployment, maintenance and support of said technologies which eases a lot of the suppot burden/overhead but also because they just work ™.

Now having said all of that, I don't see how adopting a change like this with LDAP would easily allowing us to iterate and add new features within Authelia without also being heavily reliant on user action with future upgrades. I'm personally of the opinion that upgrades to Authelia should require minimal to no action required with the ancillary services that Authelia itself requires to function.

You could argue that this should be a conscious decision by the administrator of the environment, however I think this could severly stifle how quickly we might be able to move.

I'm open to discussions around how elements that we are proposing to be managed within the SQL backends could potentially be catered for in an LDAP scenario as I'm by no means an LDAP expert, though without solving that issue I don't see how this would work.

It's worthwhile saying I by no means speak for the entire team and utlimately I would defer to @clems4ever as the project owner.
I apologise for the long-winded response and the braindump, I was just hoping to provide you with context specific to your proposal.

I hope this doesn't discourage you from contributing to the project, I personally would love to welcome new developers and encourage contributions in whatever way that is possible!

**Comment by clems4ever** [comment]
Hello @koshatul , I share the point of view of @nightah. Also, I'm not entirely against storing some secrets in LDAP in general. I've seen instances where the GPG key(s), SSH key(s) of the user were stored there for instance.

However, given the current architecture of Authelia, I'm following @nightah 's opinion. I think this change will add a lot of complexity for us and users both in terms of configuration and data management (migrations, support of partial storage in multiple backends which add specificities to take care of as maintainers). As I mentioned we try to keep Authelia as simple as possible to keep it secure, that's the ultimate goal we have over features. However, I'm not against the idea of supporting the multi availability zones setup at some point because it might make sense for resilience and costs in enterprise environments. By the way what would it cost to have only one AZ? I mean having all instances of Authelia targeting the same LDAP and backend from one DC only? It's definitely imperfect in terms of region isolation but at least you would not need to rebase your change, it's a tradeoff.

I think designing the proper solution to support multi AZ requires to take a step back and thoroughly think how we would integrate it with the rest of the application both in terms of code and configuration. We need to go back to the concepts instead of the technical details to ensure the long-term viability and security of the feature imo.

Like @nightah , I hope it does not discourage you from contributing because it's definitely not the objective but I also hope you can understand our position regarding the current change.

Please let us know what you think.

**Comment by koshatul** [comment]
Sorry for taking so long to reply, thanks for taking the time to explain the point thoroughly.

### Summary

I thought I should put a summary at the top of this before diving into details.
- MFA in LDAP means extra custom schema and further support and lack of AD/LDAP support, this would have low-adoption and a tendency to break on upgrade, requiring specific domain knowledge to repair.
- One AZ for all means latency on authorization checks, so every connection getting additional latency; and information leakage between AZ (`domain1.com` redirecting to `domain2.com` for authentication)
- Multi AZ but still centralised would still mean some information leakage as well (`authelia.domain1.com` and `authelia.domain2.com` sharing an IP from one datacenter.

Although we fit into group 3 from @nightah's [reply](https://github.com/authelia/authelia/issues/1147#issuecomment-649239315), what we're using is centralised authentication for separate entities, the entities are separate and remain separate, but we want to simplify the authentication for web resources and test environments to a single entity, this works for SSH by replicating LDAP and using LDAP/pam/nss, but isn't as simple for web.

All-in-all I think this does close out the issue, the solution isn't in MFA in LDAP, I did note that maybe a authelia-lite sidecar for centralising auth could work, but it still has the information leak issue.

### Long winded reply

Reading your point of view I can see where you're coming from, adding the MFA to LDAP means additional schema (which I don't believe there is already a MFA schema, I did create my own, but also using openLDAP and having our own OID allocation makes that easier) and something that many AD/LDAP users would not be able to consider.

codebase-wise it means maintenance of a feature that probably won't get wide acceptance, although one solution might be centralising the setup of MFA and pushing it out (so not running replicated *SQL, but using something OOB to replicate it), from authelia's point of view it would mean instead of doing the MFA setup internally, it would check if a user has MFA, if not provide a link to an external setup (and since this would also be after initial authentication, it reduces the information leak to authenticated users), it would be minimal changes to the codebase and the *SQL could even be read-only replicas from a central master.

With the current setup that could just mean disabling generating new MFA and just showing the user an error if they don't have MFA and are trying to log in to a `two_factor` resource, then company policy or if the error is customisable showing the user how to create authelia supported MFA in an intranet site.

I'd have to go back and look at it, but that would probably still be a steep change.

One AZ means information leakage (domain1.com can now been seen to be connected to domain2.com), and in the traefik/sidecar deployment it means every web request to `us.domain.com` also has a internal request to `authelia.domain.com` which might be in the `eu` adding latency to every connection.

Also the session cookie would be under `domain2.com` not `domain1.com`.

I did make a simple caching redirection traefik sidecar (so many buzzwords) so that the authentication could be offloaded to a central service (so authelia could be wherever) but once authenticated the session would be validated locally by a sidecar running next to traefik, it's quite hacky so I need to improve it, it did require a `unique-and-never-used-path` in the destination site, so the session cookie could be set inside the final domain, I'd be happy to expand upon and cleanup that code if someone was interested in it, just writing this out gave me some ideas on improving it.

It meant the process was a bit convoluted, and still had the issue of redirection information leakage, but it meant much faster post-authentication connections but still centralising the authentication.

The negative is with that method is that authorization more precise than domain scope becomes unavailable, unless the sidecar is processing a similar config or somehow forwards the scope for the session, then the sidecar only knows `user can access website.com`.

**Comment by koshatul** [comment]
I forgot to note that the use-case I have is probably fairly unique in that it's multiple domains and DC all needing to remain separate entities but still centralising the authentication.

And to remain separate means no redirection to a domain outside a single entity.
