### ISSUE TITLE
Display the links in the mails sent by Authelia to reduce likelihood of phishing

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#1149]
In order to reduce the risk of phishing, I'd rather remove the button and replace it with the link or at least have both displayed in the emails.

https://github.com/authelia/authelia/issues/965 would prevent such attack but I think most people won't verify GPG signatures so...

**Comment by TheHllm** [comment]
Correct me if i am wrong, but  could an attacker not simply display a seemingly valid url?
A better solution would be to have the user navigate to the authelia instance and enter a one time pad.
This would not solve this issue entirely, since users could still be persuaded to click a link and enter their info.

On a more general note email phishing is impossible to eliminate, given a large enough userbase.

**Comment by back2root** [comment]
@TheHllm in such cases, as described by you, E-Mail clients as well as spam filters tend to rate an E-Mail as phishing/spam.
Thus the suggested change adds a thin layer of security.

But the security benefit is quite small. Even if authelia displays the link, an attacker could still just avoid doing that. The average user doesn't know, what to expect.
