### ISSUE TITLE
Use SHA512 instead of SHA1 as algorithm for TOTP

### ISSUE THREAD

**Issue by TheHllm** [authelia/authelia#1226]
Authelia uses the SHA1 algo for TOTP, from looking at the code it is likely that the example code provided by the lib was simply used. Only 3 moths ago was the example code [changed](https://github.com/pquerna/otp/commit/d3764ecb78bcd4739b4ed86d07b75bf8965ad3ab) to reflect, that there are other choices.
Changing the algorithm would increase security, as SHA1 is [somewhat insecure](https://crypto.stackexchange.com/questions/48289/how-secure-is-sha1-what-are-the-chances-of-a-real-exploit).

This would be simple, as long as you are willing to treat all (even ones registered as sha1) as sha512,
resulting in old codes being invalid, wich would force users to generate a new secret wich would then be shiped with the new algo.
It would also be possible to make only new registraions of TOTP use SHA512 this would however require more code.

**Comment by clems4ever** [comment]
Hello @TheHllm , thank you for reporting this issue. To me, SHA-1 is not resistant to collision attacks anymore but still resistant to preimage attacks so it's safe to use it in the case of TOTP. This is because the secret is fixed and not known from the attacker, so it would require a second preimage attack weakness to exploit.

Here are the references I'm using:
* https://en.wikipedia.org/wiki/Hash_function_security_summary
* https://en.wikipedia.org/wiki/Collision_attack
* https://en.wikipedia.org/wiki/Preimage_attack

But in fact, the answer from the thread in stack overflow is smart enough to advise moving to SHA2 before SHA1 is broken regarding preimage or second preimage.

I think, in order to smoothly transition, we could add a column to the DB to store the algorithm used, default all existing rows to SHA1 and then use SHA512 for all newly created entries.

**Comment by james-d-elliott** [comment]
So I believe my PR has a working example. However there are a few caveats. Google Authenticator silently ignores the algorithm.

https://github.com/google/google-authenticator-android/issues/29

**Comment by james-d-elliott** [comment]
What I have decided to do is leave the default at sha1, and make it configurable with plenty of clear warnings (one on startup). I'm pretty sure my PR is ready to merge now.

**Comment by nightah** [comment]
So @james-d-elliott and I were discussing this again given our initial backpedal on introducing something stronger than SHA1 as a the default.

Since most password managers now also support generating TOTP keys and some of the big ones also support providing an OTP URL with an algorithm I think we can entertain the idea of bringing this back to the table.

One of the things we probably need to consider and address is removing the links to Google Authenticator and taking care of #1145. If we have a documented page we can refer to with the relative support we can look to change and strengthen the defaults.

**Comment by james-d-elliott** [comment]
I had an idea regarding this. If we maintain a list of auth apps in our docs we can link directly to that based on algo.
