### ISSUE TITLE
Using dynamic dns as networks filter

### ISSUE THREAD

**Issue by Tripton** [authelia/authelia#1245]
Hello,

I came across this cool project and it's seems to be a nearly perfect match for my situation.
But I have a question if and how a specific problem could be solved.

If have a network which has a fixed IP range which I can whitelist with the networks attribute in the config.
However, some of my clients don't have a fixed IP but have a dynamic DNS Setup which points to their dynamic IP.
I do want to also whitelist this clients.

Currently I have a custom solution which check if the IP is from the fixed ranged network.
If not I check if one of the dyndns domains point the the corresponding IPs.
I know the best solution would be, to enable a VPN connection to the fixed range network, but that is not possible in my case.

That's why I want to know if this can be solved by authelia with e.g. following configuration:

    - domain: secure.example.com
      policy: one_factor
      networks:
      - 192.168.1.0/24
      - dyndns.my-domain.com

If not, would it maybe be possible to implement?
I know it's very inefficient but using this dyndns filter is the only way to controll the acces to my server as wanted.

Thanks for your awesome work and keep going!

**Comment by clems4ever** [comment]
Hello @Tripton , thank you for reporting this proposal.

Indeed, Authelia does not support this case because I developed it for being CIDR-based at the beginning. It was made to allow different authentication levels when authenticating from LAN or WAN.

I think using reverse DNS lookup to check the domain will likely bring more integration problems due to reverse DNS not set up properly than what the feature really brings. It would probably make sense if there was no workaround for it but as you mentioned a VPN or VLAN could do the trick in this case.

So for now I'd rather not introduce the feature or accept a PR on that one because the added value is low imo. But as always, if there are more upvotes and interest around it, I can reconsider it.

**Comment by nightah** [comment]
> I know the best solution would be, to enable a VPN connection to the fixed range network, but that is not possible in my case.

I'd also been to understand this statement a little more. If you're able to host a website via any of the common reverse proxies you could probably also enable a VPN.

There are even solutions to share the same port as https with the VPN so you don't need to punch multiple holes open in your firewall.

**Comment by clems4ever** [comment]
I'm closing this issue as it did not bring enough interest so far, certainly because there are better solutions to solve the problem.

**Comment by james-d-elliott** [comment]
We would accept a template function that resolves a string to an IP, and errors if it can't (halting startup).
