### ISSUE TITLE
Question: Does authelia support any patterns for non-interactive authorization

### ISSUE THREAD

**Issue by bashirsouid** [authelia/authelia#1298]
Hi team,

Sorry for the noob question; just researching the project to learn more before I try it out for a project. If this is not the desired way to ask questions like this then feel free to close or delete this issue.

This project looks great for interactive login scenarios where there is always a front-end experience available for user to login with single factor or two factor authentication. I was wondering if there are any patterns people have followed with authelia for API-only scenarios where there is no interactive login.

Some examples of how some services achieve this is with scoped user access tokens (like Github supports). These inherently have some security implications due to these tokens being long living, never expire unless revoked, etc. But have proven to be a valuable to people because it is easier to integrate into automation scripts, etc.

Are there any similar patterns you are aware of that people leverage authelia to do similar to support completely headless scenarios? Or maybe this is not really the scope or intended purpose of the project so not applicable?

Thanks for all your hard work developing such a great looking project!

**Comment by bashirsouid** [comment]
Reading the docs more... I guess you could use network based authentication configuration rules to do things like service-to-service authentication between backend services behind the proxy to trust one another implicitly... so if you needed to do some automation or maintenance script you could deploy it as a docker container to the pool and make any calls as necessary.

https://www.authelia.com/docs/configuration/access-control.html

**Comment by nightah** [comment]
Hi @bashirsouid thanks for your interest in the project, as you have surmised from reading the documentation the network based authentication is probably one of the best candidates to achieve the suggested outcome.

There are alternatives like in single factor scenarios and the use of the [`Proxy-Authorization` header](https://www.authelia.com/docs/features/single-factor.html#proxy-authorization-header) but be aware that this does not work with Traefik currently because of the fact that the header is considered hop-by-hop and is stripped.

There's also work being done to introduce OIDC/OAuth2 scoping into Authelia so that will likely open a few more doors in the near future.

**Comment by nightah** [comment]
@bashirsouid did you have any other questions or are you happy for me to close this off?

**Comment by bashirsouid** [comment]
No other questions. This is all great. Thank you so much!
