### ISSUE TITLE
Misleading docs related to session cookie?

### ISSUE THREAD

**Issue by chris13524** [authelia/authelia#1411]
On the [session docs](https://www.authelia.com/docs/configuration/session.html) it says that `session.secret` is used to "encrypt the session cookie". Which to me, means the cookie sent to the user's browser is encrypted. However, looking through the source code I never see `SessionConfiguration.Secret` used outside of Redis code blocks. [This](https://github.com/authelia/authelia/pull/789/files#diff-9e2351f62725f17ebbfe9b0db5b6510f234ae1f25fbc641a80f2c767b1695397R248) also indicates that `session.secret` is only used for Redis.

Should the docs be updated and/or this configuration option moved into the `redis` config block?

**Comment by james-d-elliott** [comment]
So we can definitely update the docs to make it more clear. There is no tangible benefit to encrypting the cookie on the client more than it is (we set the secure attribute, which prevents it being sent over http). The cookie is random data, which has no relevant purpose client side other than to be sent to Authelia in order to match the client to a session.

If we add encryption to the random data, either the server has to decrypt it (no security benefit), or the client does (marginal security benefit since if someone compromises the client they can obtain the details needed to decrypt it). The standard applicable security practice here is to never store anything sensitive (i.e. user details) on the client, you store everything server side except the one thing to link it all together.

We used to encrypt the session data in memory (i.e. without redis), and I have a feeling that is still the case, but I'll have to verify that (even though it is only has a minimal security impact).

**Comment by chris13524** [comment]
Ok I see. Yeah, I agree that there would be no need to encrypt a token sent to the client. Unless it was JWT or something like that, which is one of the things I was considering as a possibility of what the docs were referring to. But it's not that, so it doesn't matter.

From my research, `Secret` is only used by Redis code, not in-memory storage.
