### ISSUE TITLE
The Authelia service is stuck in a reboot loop due to health checks.

### ISSUE THREAD

**Issue by AndreiArdelean1** [authelia/authelia#1442]
The Authelia service is stuck in a reboot loop because the health check is done for port 9091 while configuration.yml specifies a different port.

Authelia logs:
time="2020-11-10T13:38:08+03:00" level=info msg="Logging severity set to debug"
time="2020-11-10T13:38:08+03:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2020-11-10T13:38:08+03:00" level=debug msg="Storage schema is up to date"
time="2020-11-10T13:38:08+03:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
time="2020-11-10T13:38:08+03:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:7091/authelia"

Portainer error message:
`
Error message | task: non-zero exit (2): dockerexec: unhealthy container
`

#1425

**Comment by nightah** [comment]
Thanks for the report @AndreiArdelean1 given that we don't have a lot of control over whether a user does or doesn't change the default port our recommendation would be to change the healthcheck command.

If you create the container via your [`docker run`](https://docs.docker.com/engine/reference/run/#healthcheck) command append `--health-cmd wget --quiet --tries=1 --spider http://localhost:<REPLACEYOURPORTHERE>/api/state || exit 1` replacing the `<REPLACEYOURPORTHERE>` placeholder.

If you run it with a [`docker-compose.yml`](https://docs.docker.com/compose/compose-file/#healthcheck) change the `healthcheck` key:
```yml
healthcheck:
  test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:<REPLACEYOURPORTHERE>/api/state", "||", "exit", "1"]
```

**Comment by nightah** [comment]
Also it's worthwhile clarifying, is there a specific reason why you have changed the default port in a Docker based deployment?

If you plan to expose it up to the host couldn't you just specify a different host port?

**Comment by AndreiArdelean1** [comment]
I don't believe this to be a solution since it introduces unnecessary complexity to the docker installation. Your solution is more of a temporary fix. 

I see a few options:
1. creating a healthcheck script within the container that would use the actual port.
2. disabling the changing of port option within the configs
3. exposing a constat port that would redirect to the port used
4. disabling the healthcheck altogether since it was working fine before
5. 2 + setting the port from an environment variable that can be set from a docker stack and its accessible from the docker file

**Comment by AndreiArdelean1** [comment]
I changed the port because that port was already used by another service. I fixed the issue by disabling the healthcheck. I could have also used the default port internally and exposed a different port from docker. The problem is that the healthcheck is breaking an existing feature (setting the port) and requires fixing on the user side.

**Comment by nightah** [comment]
We wouldn't entertain the idea of removing the ability to change a port because that's looking at deployments of Authelia with a very narrow view.

As of the time of writing this message it's available as an OS package in Arch, FreeBSD ports and users can download the static binary to run on bare metal.

The issue is specific to your deliberately changed setup.
You've acknowledged that you could leave the internal port for docker as the default and expose it different to the host.
There are also multiple mechanisms for you to either change or disable the health check.

Having said that I wouldn't be averse to adding something to the documentation and/or updating the entry point script to determine the port/healthcheck URL from the `configuration.yml`.

**Comment by AndreiArdelean1** [comment]
> The issue is specific to your deliberately changed setup.

Yes, the issue is due to deliberately changing the `configuration.yml` but generally, changing one simple parameter (such as the port number) shouldn't result in the app no longer working and in the need for additional configurations. Regarding health checks, I agree, they are nice to have but in my opinion, they can be removed for now and added back when they are done right.

To me, it makes more sense that the users who want health checks can manually include them since the app is working without them instead of having the app crash for users who changed the port number and didn't change the health check.

**Comment by Ornias1993** [comment]
@AndreiArdelean1 You can easily just pass the healthcheck disable to your docker command.

I AM in favor of adding more documentation about the healthcheck though and looking into iteration on the healthcheck to make it more solid...

@nightah Can we set something like an env-var with the port, create "healthcheck.sh" that uses said env-var instead of a fixed port? That would be a relatively easy fix.

I rather have iteration on work, instead of removing it because a user has a customisation.

**Comment by nightah** [comment]
Adding in the `--start-period=1m` option per @Ornias1993 in the PR would prevent the reboot loop and instead would suggest that your container is unhealthy.

This technically would resolve your issue while still bringing healthchecks to everybody else without any issues.
I've already got a PR with this up and running and am looking at dynamically determining the scheme and port for Authelia in a healthchecks script too.

Either way we'll have a fix in soon.

**Comment by Ornias1993** [comment]
> Adding in the `--start-period=1m` option per @Ornias1993 in the PR would prevent the reboot loop and instead would suggest that your container is unhealthy.

No, that would still restart, it just ignores failed healthchecks done before 1m after start of the container ;)

**Comment by nightah** [comment]
> No, that would still restart, it just ignores failed healthchecks done before 1m after start of the container ;)

I do not believe that to actually be the case, my own testing yesterday suggested otherwise, I had an unhealthy container running for over 15 minutes.
Effectively it seems because the container never received a "healthy" ping it does not seem to reboot the container.

Also per the following [source](https://github.com/docker/cli/blob/5bf86c198488c7f78f2ffd05a8a2441f719d3b98/docs/reference/builder.md#healthcheck)

> **start period** provides initialization time for containers that need time to bootstrap. Probe failure during that period will not be counted towards the maximum number of retries. However, if a health check succeeds during the start period, the container is considered started and all consecutive failures will be counted towards the maximum number of retries.

**Comment by Ornias1993** [comment]
>  However, if a health check succeeds during the start period, the container is considered started

Interesting, never looked at it that way.
