### ISSUE TITLE
Returning login page (200) for all paths is dangerous

### ISSUE THREAD

**Issue by ThinkChaos** [authelia/authelia#1520]
This seems dangerous as a single typo in the reverse-proxy config could send requests, for example, to `/api/verifi`, authelia would reply with a 200 and the original request would go through.

From what I gather (haven't looked at the code):

 - `/static/*` serves files, or a 404
 - `/api/verify` works as expected
 - `/*` serves the login HTML

So in case of a typo, `/api/x` hits `/*` which returns a 200, except if x is one of the other existing endpoints like state or info, but for a typo that is extremely unlikely.
An admin would likely quickly notice their server is entirely unprotected, but it's better to not make this situation possible.

I propose only returning the login page for `/`, and returning an error by default.

**Comment by nightah** [comment]
This behaviour is intended and implemented as such because of the routes the frontend serves with React's Browser Router.

If you were to the remove this behaviour from:
https://github.com/authelia/authelia/blob/c14af472dd124fa782b73a33ffc118bfcc80a1c6/internal/server/server.go#L125

It would result in unintended 404's on page refreshes, you would only be able to visit the root path `/` to be redirected to the correct frontend page, you can test it yourself to see the behaviour with and without.

The flipside of the argument is that we could implement a route for all of the frontend paths too and redirect that to the indexhandler but I think that's a whole bunch of unnecessary code to cater for a potential misconfiguration issue.

**Comment by ThinkChaos** [comment]
How about at least returning an error for unknown routes under `/api`?

**Comment by clems4ever** [comment]
Fair enough, I did the change for /api/*. We can merge it if my colleagues approve the change but please note that it does not make the API any more secure.
