### ISSUE TITLE
Customizable logo & favicon

### ISSUE THREAD

**Issue by TheCatLady** [authelia/authelia#1630]
Would love to see an option to customize the logo and favicon!

![image](https://user-images.githubusercontent.com/52870424/105633364-193b0a80-5e26-11eb-9b2b-d7610dbddddd.png)

**Comment by fabriziorizzo** [comment]
Regarding the Sign Out use-case, it would be nice to include the User's display name with the "Sign Out" text. 

Should this be a separate issue?

**Comment by TheCatLady** [comment]
> Regarding the Sign Out use-case, it would be nice to include the User's display name with the "Sign Out" text. 
> 
> Should this be a separate issue?

Not sure how that is related to this issue?  🤔

**Comment by hutch0** [comment]
If the logo is being customized, it would be nice to be able to easily change the color of the text box selection and sign in button, just to match to the logo and favicon.

OTOH, if we could break out a few pieces of CSS that could be set as variables, and read in as text files, we'd have the beginning of themes. Since the page is so basic, it would really just be text box selection and background color, page background color, logo, favicon, font, and maybe checkbox style. That's a whole bunch of creep to your issue though, and I think just being able to change the text box selection and sign in button color to match the logo would be really nice.

**Comment by Kippenhof** [comment]
i would like it even better if there was an option in the rules to specify a path to the desired image for each rule. that way you could specify the image after the web app you want to protect.

**Comment by FinalDes** [comment]
anyway to customize the login page

**Comment by loftwah** [comment]
I can make a way to do this with Docker by mounting a custom file to the favicon path in the application.

**Comment by loftwah** [comment]
In Docker-Compose it might look like this

```yaml
  - ./app/favicon.ico:/path/to/authelia/favicon.ico
```

**Comment by loftwah** [comment]
https://gist.github.com/loftwah/4afb2d71d02cc59953b85c87fad00059

**Comment by nightah** [comment]
The static assets are not found in a location within the Docker container, they're embedded directly into the Authelia binary so unfortunately what you have suggested above will not work.

There will need to be a code change in Authelia for this to work. I'm intending to do this relatively simple change soon unless someone else wants to pick up the task.

**Comment by loftwah** [comment]
Really? Wow, I haven't seen that for a while. I can have a look at it.

**Comment by nightah** [comment]
Ping to those subscribed, please feel free to try the `feat-custom-assets` tagged Docker container.

You'll need to configure the `server.asset_path` key in your configuration, for the other specifics please refer to the docs:
https://github.com/authelia/authelia/pull/2597/files#diff-200f5664618645a083965f4681ffffcb942582f51a9ea18baa976cd320e1413dR90-R223 and let me know if you have any questions/issues.

**Comment by esmoyer** [comment]
This is great! Just gave it a try. Got the logo to work, but can't get the favicon to change. I have it as an .ico file (previously used for a couple other services I host), tried clearing cache and even tried in-private and a separate browser, but doesn't seem to want to change. Is it possible I missed something?

**Comment by nightah** [comment]
@esmoyer that's odd, I've just tried it again successfully so I'm unable to reproduce your issue.

What happens when you visit the favicon path directly `https://auth.example.com/favicon.ico`?
Do you see the embedded favicon or the one you have attempted to override with?

Also just to confirm it's definitely in your `server.asset_path` (assuming it's `/config/assets/` as `/config/assets/favicon.ico`)?
Have you attempted it with a different favicon just to rule that out as the problem?

Once I put a favicon in the path, I just perform a hard refresh (Ctrl + F5) and it updates immediately, no restart required.

**Comment by esmoyer** [comment]
Yep, that all checks out. I'll keep toying around with it, I wonder if Cloudflare is still caching the old one or something. Not a huge deal. Thanks!

**Comment by LeehamElectronics** [comment]
@nightah how do I find where my `server.asset_path` is? I am running Authelia in a docker container on an Ubuntu server. I have tried dropping a` assets/logo.png `into the same folder that contains my Authelia config file and users file, and I have also tried putting it in the  `/config/assets/`. What else can I try?
Thanks

**Comment by james-d-elliott** [comment]
https://github.com/authelia/authelia/blob/master/config.template.yml#L47

**Comment by LeehamElectronics** [comment]
> https://github.com/authelia/authelia/blob/master/config.template.yml#L47

Thanks that worked, any chance we can change the "powered by Authelia" text as well? Thanks

**Comment by m4heshd** [comment]
@james-d-elliott Works perfectly. Thank you.

It seems like the original logo image is an SVG (inline). It would be great if us too could use an SVG. Also there seem to be no way to change the login page title. It's always **"Login - Authelia"**.

**Comment by james-d-elliott** [comment]
Open another feature request regarding changing of the title / text of the portal. You'll probably want to provide a use case.

As far as the SVG we decided against this as most people don't know how to produce a SVG and the image would not render with the benefits of the SVG most likely. We're definitely not prioritizing it as it is more of an enhancement and the original feature implementation works. It'd probably good to open another issue regarding this too, otherwise contributions are always welcome.

**Comment by Henkow** [comment]
> Ping to those subscribed, please feel free to try the `feat-custom-assets` tagged Docker container.
> 
> You'll need to configure the `server.asset_path` key in your configuration, for the other specifics please refer to the docs: https://github.com/authelia/authelia/pull/2597/files#diff-200f5664618645a083965f4681ffffcb942582f51a9ea18baa976cd320e1413dR90-R223 and let me know if you have any questions/issues.

I have tried this on 4.34.6 and the latest version but neither the logo or icon change when I use server.asset_path = /config/assets. I've put both files named correctly within said folder. I have restarted authelia and cleared cookies to no avail. I'm running authelia in a docker container if that matter. Any idea what I can try? Thanks.
