### ISSUE TITLE
Dark Theme Too Dark

### ISSUE THREAD

**Issue by idcmp** [authelia/authelia#1777]
I've tried on a few QR code scanners now, and the contrast of the QR code against the 'dark' theme background is insufficient for it to be picked up - switching to the light theme and the code is picked up immediately.

**Comment by james-d-elliott** [comment]
So in testing we could not replicate this, but due to there being differences in camera quality, monitor temperature and color accuracy, and many other factors it may be beneficial to add a white 1px border to the image. Do you know how to manually edit this locally using browser tools to test?

**Comment by Shiwigy** [comment]
I suffer the same problem with the dark theme activated, using Galaxy S10.
The problem is that the container holding the QR-code has the dark background color wich will confused the scanner.

It can easily be solved by adding background-color: #fff to .jss10, se below.

```
.jss10 {
    background-color: #fff;
}
```

**Comment by clems4ever** [comment]
I've done a fix to help with this issue. I added some padding around the qrcode so that the border is more obvious to the qrcode readers. It should prevent the issue I think.

Here is the outcome:
![qrcode authelia](https://user-images.githubusercontent.com/3193257/121806860-e0bf9000-cc51-11eb-9f07-6eb9c6e564f0.png)

**Comment by idcmp** [comment]
Can confirm FreeOTP picks up the QR code in that screenshot effortlessly.

Thank you!
