### ISSUE TITLE
Yubikey not working on Microsoft Edge 89.0.774.54

### ISSUE THREAD

**Issue by marcelhoffs** [authelia/authelia#1832]
When doing 2FA with a Yubikey it does not work on Microsoft Edge.
I get a red popup message: **"Failed to initiate security key sign in process"**

The same works just fine on Firefox 86.0.1.
Is there some setting in MS Edge that needs to be enabled to make this work?

On de browser console I see this:
_Error: U2F not supported
    at p (u2f-api.js:73)
    at u2f-api.js:120
(anonymous) @ SecurityKeyMethod.tsx:80_

Though I can use my Yubikey fine in MS Edge for things like my Google Account, Bitwarden, etc.

**Comment by james-d-elliott** [comment]
Sadly Edge doesn't support U2F at all. It supports Webauthn which is considered a replacement technology. We have as yet implemented it, as we're hard at work on other things. The plan was to implement it at the same time as multi-key functionality which would likely accompany a settings UI.

**Comment by marcelhoffs** [comment]
Ok good to know. In that case I will be using Firefox for now then :)

**Comment by clems4ever** [comment]
Hi,
Webauthn is definitely high in my wish list because I'd like to use fingerprint authentication with my mobile. That would be awesome. But we'll discuss the priorities again once we're happy with OIDC which is the next coming big thing.

Sorry for Edge @marcelhoffs ...

I'm closing the issue for now. Thanks for reaching out in the meantime.

**Comment by james-d-elliott** [comment]
Follow issue #241
