### ISSUE TITLE
authelia shouldn't attempt to remove notification file

### ISSUE THREAD

**Issue by yurivict** [authelia/authelia#1846]
I run Authelia as the user 'nobody' with /var/db/authelia-notification.txt owned by 'nobody'.

However, during startup Authelia attempts to remove this file and fails:
```
time="2021-03-22T19:32:35-07:00" level=fatal msg="Error during notifier startup check: remove /var/db/authelia-notification.txt: permission denied" stack="/wrkdirs/usr/ports/www/authelia/work/authelia-4.27.2/cmd/authelia/main.go:112                     startServer\n/wrkdirs/usr/ports/www/authelia/work/authelia-4.27.2/cmd/authelia/main.go:137                     main.func1\n/wrkdirs/usr/ports/www/authelia/work/authelia-4.27.2/vendor/github.com/spf13/cobra/command.go:856 (*Command).execute\n/wrkdirs/usr/ports/www/authelia/work/authelia-4.27.2/vendor/github.com/spf13/cobra/command.go:960 (*Command).ExecuteC\n/wrkdirs/usr/ports/www/authelia/work/authelia-4.27.2/vendor/github.com/spf13/cobra/command.go:897 main\n/wrkdirs/usr/ports/www/authelia/work/authelia-4.27.2/cmd/authelia/main.go:154                     main\n/usr/local/go/src/runtime/proc.go:225                                                             main\n/usr/local/go/src/runtime/asm_amd64.s:1371                                                        goexit"
```

There is no need to remove it, and such removal is also impossible in the conditions of minimal permissions.

**Comment by nightah** [comment]
@yurivict we actually perform that check to truncate the file, but really it isn't necessary.

If you get a chance can you please try build https://github.com/authelia/authelia/commit/ff36950a222d70b07fe8802980862488058d3fb8 and check to make sure your issue is resolved?

I attempted to replicate the use case with Docker and while it fixed the startup check running as the user `nobody:nobody` I couldn't update the SQLite storage backend, though I think this was more of a Docker nuance as opposed to anything else.

I'll put a PR up in draft pending your feedback.

**Comment by yurivict** [comment]
It doesn't try to delete the file with rev. ff36950.

**Comment by nightah** [comment]
Yep I confirmed that element, I was hoping you might have the opportunity to test on your baremetal setup to see that the portal and login/logout works as expected because I had some odd behaviour when running as `nobody` with Docker.

**Comment by yurivict** [comment]
The login prompt showed up but I am not a user, and have no authentication DB set up, sorry.
