### ISSUE TITLE
2FA : Send verifications codes to mail ?

### ISSUE THREAD

**Issue by Nico83500** [authelia/authelia#2035]
Hi,
I would like to know if there is a way to use 2FA by sending verification codes to mail ? A 6 digit verification code is sent by mail in order to authenticate the use.
Thank you.

**Comment by AlexGustafsson** [comment]
Just chipping in to say that it's not really 2FA. Typically, two factors refers to two of three categories; something you know, something you have and something you are. That is, passwords, keys and biometrics. In this case, e-mail is just another service protected by a password (something you know) - so it's not really a second factor to the password you already use to login to Authelia. Although I've seen some services make use of such ways to authenticate their users, it's perhaps a bit questionable from a security standpoint.

**Comment by Nico83500** [comment]
Thank you for these informations, you're right. Even it's a 2FA, perhaps it could be added as an additional security feature for 1FA ? Thank you.

**Comment by AlexGustafsson** [comment]
It should be rather easy to do if #2023 is done general enough. That way, one could use the same mechanics to create a single-use token valid for authentication only, which may be sent by mail. The mail would contain the token in a query parameter which the frontend would use to try to authenticate the user via the existing APIs.

**Comment by clems4ever** [comment]
I'm not totally against it since I also see other services doing this kind of 1FA but this is definitely not our priority at the moment. However, contributions are always welcome. For any non-trivial contribution I advise to reach us on Matrix so that we can design it together and make sure we all agree on what it should be before any code is written.

**Comment by AstralDestiny** [comment]
Even though emails are literally plaintext in the end for the majority of people who use them, One_Factor in the end with mail wouldn't it be 1.5FA?

**Comment by ryanjaeb** [comment]
A feature like this would be useful for gating access to resources that use standalone (aka built-in) authentication.  As an example, I'll often spin up a Docker container to try out a product.  I'll accept all the default config and use the built-in authentication because I'm evaluating features, not security (initially).  I'm always hesitant to expose that kind of thing to the internet, but I'll often want to let others try it out while I have it running.

The ideal scenario for me would be to supply a list or regex of email addresses that are allowed to access a resource.  Requests for that resource would prompt for an email address and, as long as that email address is on the allow list, a single use token is sent via email.   In my case, I find it useful to have the authentication period last for a while (1 week+).

Cloudflare Access has something similar and they call it one-time-pin authentication.  I personally don't treat it like normal authentication though.  I view it as device pre-authentication that's useful for limiting attempts to access protected resources.  Forcing all login attempts through even a minimal amount of forward authentication has value in my opinion.

It could probably even be designed as an *additional* check initially.  If you log in from an unknown device, you get prompted for an additional token that's sent via email.  I believe Steam Guard would be a good real world example.  If you try to access a Steam account from a new device, they send you an email with a one-time-code that you need to provide before logging in.  The one-time-code is being used to limit authentication to well known devices.

**Comment by james-d-elliott** [comment]
Rolling this up into #3801

**Comment by mgabor3141** [comment]
@james-d-elliott This feature did not end up in the final design as far as I can tell, or at least I can't find a reference to it in the documentation. Would it make sense to reopen the issue?

**Comment by james-d-elliott** [comment]
@mgabor3141 

So in the process of working on that feature it became clear to me that a code sent to an email is not sufficient to consider it MFA, since there is no known factor involved in the email itself, making it solely another channel.

In addition the rampant availability of MFA technologies like webauthn/passkeys make this almost a negligible issue.

I'm not personally a fan of this authentication measure either, it's a nice stopgap for people who've not configured MFA but otherwise as stated [here](https://github.com/authelia/authelia/issues/2035#issuecomment-851016691) it's not really MFA.

That being said I'm willing to consider it as part of the overhaul to the policy levels via [this roadmap item](https://www.authelia.com/roadmap/active/granular-authorization/), where administrators would explicitly opt-in to a custom policy that allows this.

If this is desired I can convert this to an idea discussion and we can leave it open for that purpose. I can start cataloging these things for the AMR process which is a massive impactful security change to Authelia.

**Comment by n0rad** [comment]
Actually to me it may be an MFA since the email service may be behind something that could have MFA.
So it's more somewhere between 1.5FA (2 things you know) to 2FA depending on the setup of the email service.

Plenty of usual services are introducing this workflow because it's easy and well understood by users. It's the same workflow as doing a password reset that everybody is well aware of.
On the other side, webauthn is not available everywhere (I still don't know how to make my phone browser use my fingerprint on authelia), and OTP is hard to understand for users.

I don't think Authelia should consider emails as MFA, but providing the feature as something between `one_factor` and `two_factor`  would already be a great improvement, especially since it's already able to do it for enrollment.

**Comment by Crowley723** [comment]
> Actually to me it may be an MFA since the email service may be behind something that could have MFA. So it's more somewhere between 1.5FA (2 things you know) to 2FA depending on the setup of the email service.

The key issue with this is there is no way for Authelia to know what level of authentication the user's email is protected by. Additionally since email services are generally managed by a 3rd party with root access to services, its possible emails can be intercepted without the knowledge of the user.
> Plenty of usual services are introducing this workflow because it's easy and well understood by users. It's the same workflow as doing a password reset that everybody is well aware of.

Just because everyone does it doesn't make it right or correct. Regardless this is being considered for an opt-in feature.

> On the other side, webauthn is not available everywhere (I still don't know how to make my phone browser use my fingerprint on authelia), and OTP is hard to understand for users.

WebAuthn is still fairly new and browsers are slowly adding support for it across different devices. You might give it another try, it started working for me on my mobile device.

> I don't think Authelia should consider emails as MFA, but providing the feature as something between `one_factor` and `two_factor` would already be a great improvement, especially since it's already able to do it for enrollment.

If we add it as a possible multi factor method, as mentioned it would be opt-in and the admin would have to create a custom policy that includes it.

**Comment by james-d-elliott** [comment]
We may reconsider this after we've implemented an Admin UI (super high interest), SAML 2.0 (super high interest), several of the OpenID Connect 1.0 specs which augment the existing implementation (high interest), OpenID Connect 1.0 Relying Party support (super high interest), and AMR based auth flows (major security enhancement allowing admins to highly customize the auth experience), not before. The last one is something we'd strictly make this feature contingent on if we implemented it. It's a _**super low**_ priority.

Email like SMS is never multi-factor authentication and lacks a factor element at all, at most it's multi-channel authentication without knowledge of the factors used (the email address reasonably could be publicly accessible). A strong password policy (24+ characters) is significantly more secure than email/SMS for a secondary factor. When conveying the auth level to third parties if implemented, email or SMS will never list the `mfa` or `mca` method reference i.e. it's not MFA'd or officially MCA'd.

I think we'd need an idea discussion with a significant number of upvotes to spend any serious time considering this. I can either convert this to one or a new one can be created.
