### ISSUE TITLE
"proxy" username + password for unsupported Webapps to enable SSO for "everything"

### ISSUE THREAD

**Issue by theoneandonly-vector** [authelia/authelia#2208]
### Description

I have a few Applications which are not compatible with oauth (or even SAML) and they won't be in the near future.
But all of them have LDAP-Support.
So the best solution for me would be to cache the entered creds and automatically log in the users with their own credentials on all the websites as long as they are able to authenticate against authelia.

**Comment by theoneandonly-vector** [comment]
maybe this can be done in a similar way like phishing tools do.
https://github.com/kgretzky/evilginx2

**Comment by james-d-elliott** [comment]
I'm not inclined to think this is a very good idea. Can you point to any other identity providers that do this as well as some apps that don't support header, SAML, or OIDC SSO?

**Comment by theoneandonly-vector** [comment]
maybe my problem is that I have no starting-point / idea on how to integrate this.

But I think for example this (html5 rdweb):
https://www.google.com/amp/s/msfreaks.wordpress.com/2018/10/06/remote-desktop-html5-client-on-windows-server-2019/amp/
isn't compatible..

or his one:
https://www.innovaphone.com/en/myapps/what-is-myapps.html

besides these two there are many niche products which aren't public and may be "to hard" to integrate for me. having a simple approach which works just by automatically filling out a login-form and hit "login" would make it really easy for someone like me to get started quickly.

and no, I don't know of any other system doing this.. otherwise I might be using it rn.
 is SAML coming to authelia?

**Comment by theoneandonly-vector** [comment]
question2:
rhis looks like it does something similar:
https://www.fastvue.co/sophos/blog/active-directory-sso-authentication-in-transparent-proxy-mode/

**Comment by james-d-elliott** [comment]
> question2:
> rhis looks like it does something similar:
> https://www.fastvue.co/sophos/blog/active-directory-sso-authentication-in-transparent-proxy-mode/

That appears to me like it's using Active Directory login packets to determine the IP address of the user who is theoretically logged in. This is used for firewalls to reduce the need to use captive portals to capture the logged in users identity, it would require the backend app supports this method. In this case Sophos XG does support it, fastvue I've never used so am only guessing based on their docs that they probably do as well.


A few other issues related to the original request:

1. The only realistic method of implementation is as you said storing the username and password of the user to reauth
2. In addition the only realistic workflow for this seems cumbersome and I can't see an alternate solution to this problem. See below:
    - user visits https://app.example.com
    - proxy forwards the verify request with available cookies
    - authelia checks if the expected cookie exists
     - if the cookie doesn't exist they will have to be redirected to authelia and:
        - authelia makes the relevant form POST/GET
        - authelia captures the cookie from the backend
        - authelia sets the cookie for the user so they're authenticated
        - authelia redirects the user to the app
3. We or the admins would have to add a configuration for each application that needs this.
    - each application will have different expected form inputs
    - each application will have a different path for the form
    - each application will have a different cookie name which we'd have to apply to the user
    - most applications do not need this as they support a standard SSO method

**Comment by theoneandonly-vector** [comment]
hey there
I'm very thankful that you list all the technical details.

2:
If it's possible for authelia to detect if we're still logged in to the app, it could just login the user automatically again without having the same session-timeout.

3:
wouldn't it be possible to create modules for each Service after we have one wokring implementation-template?
so every user can implement this part on their own and contribute as soon as it works as expected?

4:
as the feature should be optional we could add a warning to the docs.
also what exactly is the danger here? MITM?

5:
Is it needed to log-out the user? couldn't the user in authelia itself just be logged out (and the cookie dropped)?

**Comment by theoneandonly-vector** [comment]
do you have a different idea how I could integrate:
https://www.google.com/amp/s/msfreaks.wordpress.com/2018/10/06/remote-desktop-html5-client-on-windows-server-2019/amp/
?

**Comment by james-d-elliott** [comment]
Not specifically that, but I believe Apache Guacamole will work with the header auth.

**Comment by theoneandonly-vector** [comment]
Lat time I used Guacamole I had mostly these two problems:
1. very, very bad performance whe you use google maps or similar (overall
worse perfromance than the rdweb)

2. clipboard only copying text.

rdweb seems to be the only solution to get a somehow smooth rds experience
when using any linux client.

James Elliott ***@***.***> schrieb am Fr., 30. Juli 2021,
05:05:

**Comment by theoneandonly-vector** [comment]
https://blog.bio-key.com/form-based-authentication-sso-alternatives

isn't this what I mean?

**Comment by theoneandonly-vector** [comment]
https://support.kemptechnologies.com/hc/en-us/articles/115003813623-Form-based-to-Form-based-Authentication

**Comment by theoneandonly-vector** [comment]
video demo:
https://youtu.be/q7p-ceHZDVU

**Comment by purebordem** [comment]
Just tagging in here on the question of...

```
applications that support LDAP but don't support one of the following SSO methods:
Request Header
OpenID Connect
SAML
```

All the native app's built in Synology NAS essentially use an API for login. Essentially their login mechanism  is done programmatically or via form-data. Boils down to...

`https://<ADDR>:5001/webapi/entry.cgi?api=SYNO.API.Auth&version=6&method=login&account=<USER>&passwd=<PASSWORD>`

The app then verifies either against local accounts, LDAP, or Domain accounts. While they "have OIDC support" it is extremely barebones and only works with Azure or Websphere. They also have their own native SSO/2FA/Passwordless login system, but it only works for their apps.

Should a product this popular be more up-to-date? Very much so. But alas, here we are.

**Comment by theoneandonly-vector** [comment]
another solution which supports form -> form SSO.
https://f5-agility-labs-iam.readthedocs.io/en/latest/class7/module1/lab5.html

**Comment by theoneandonly-vector** [comment]
another one:
https://www.ibm.com/docs/en/sva/7.0.0?topic=solutions-single-sign-using-forms

**Comment by purebordem** [comment]
Looks like Bio-Key has some sort of form-matching template system for legacy app integration. Not sure what that actually looks like thought since the website is very fluffy with sales

https://blog.bio-key.com/form-based-authentication-sso-alternatives

**Comment by mnorrsken** [comment]
This sounds like supporting bad legacy applications which will create a bunch of security risks and complicate the codebase.

I have been working with this kind of software (from an "enterprise" security/IDM company) and it's horrible and even if they have a whole bunch of ways to aquire and pass along the user data, it's often not enough, and I had to resort to writing java class addons.

You will have to support Basic auth, kerberos, NTLM, form injection, custom cookies... its just not worth it in my opinion.

**Comment by james-d-elliott** [comment]
> Websphere

Technically we could support the websphere login in all likelihood. However I don't think it's a good idea to start the precedent of supporting non-standard systems. I would realistically expect they just add a custom one since they already basically support OIDC.

> another one:

Thanks for all the links. I think realistically I need input from @clems4ever and @nightah - I personally feel similar to @mnorrsken that this will become a security problem and that it's opening a can of worms for things we support.

The only potential way we can realistically support something like this is by supporting storing credentials in effectively plain text (reversible encryption to reduce chances of compromise, but it's reversible which means it's prone to be vulnerable if leaked/stolen).

Now that I think of it an alternate is if all systems share passwords then we could have Authelia login on the users behalf at the moment of the user logging in (thus only storing their provided credentials at the time of login) and store cookies to pass to the proxy. Users would have to configure login forms (path, fields), logout forms, etc. CSF tokens would be another complication (same as the other idea).

**Comment by nightah** [comment]
I'm inclined to agree with @james-d-elliott, I personally would rather not invest time in a method that's very niche and non-standard.

There's plenty of actively utilised SSO standards like SAML, Open ID Connect, KRB/NTLM and it also ounds like KRB/NTLM is something that could potentially resolve/allay some of the shortcomings of the apps in question, however that's just in the design phase at the moment.

Unfortunately I just don't think there's really a strong enough case to support this specific scenario.

**Comment by theoneandonly-vector** [comment]
Most apps are "niche", sure. But it would allow an integration for more apps than any SSO-Standard can offer today or in the next 10 years.
for sure it would make tools written by single developers or small teams (or my examples Microsofts HTML5 RDP-Webclient & Innovaphone myapps) usable in current days which would help to allow smaller companys to succeed instead of leaving absolutely everything to monopolists.
As I linked you already for bigger companys there's always a premium way like F5 which are often just not suitable for small companys so they just go to Azure.. maybe we're all gonna be happy in 20 years when there's only a few really big companys left and IT will consist of "Subdway and Macdonalds" so to speak.

**Comment by james-d-elliott** [comment]
This feature is not going to be implemented at this stage and as such I'm closing this issue. This is for the following reasons:

- This functionality could reasonably be implemented via a shim application between the reverse proxy and the backend application that does this rather than Authelia , this in between location seems like a better fit to me as all the implementations listed use this method, it's far more complicated to implement it in the architecture that Authelia utilizes. 
- No compelling reasons have been provided that counteract the cost of implementation and potential security issues and liabilities involved
- No method currently exists to implement this within Authelia neatly as users would have to do something to allow Authelia to set the required cookies for this domain in their RP config different to nearly every other webapp
- The configuration elements involved is limitless as not every webform is created equal:
  - Some forms use POST with query args
  - Some forms use POST with form data
  - Some forms use GET with query args
  - Some forms use CSRF
  - Some forms even use proprietary encryption which would all but be impossible for us to implement
  - Some forms use websockets which would all but be impossible for us to implement
  - Some forms use something we've not even thought of
- Handling logouts is important and not a trivial thing to do.
- When looking at all of these potential issues regarding implementation and how much work implementation will cost, then comparing it to the lack of interest and lack of use cases (i.e. there have been only 2 or 3 applications listed), it doesn't seem like a good time investment
