### ISSUE TITLE
Logout all sessions of current user

### ISSUE THREAD

**Issue by ViRb3** [authelia/authelia#2280]
This would be the equivalent of "Log out from all devices" found in various other online services.

The use case is this - you log in somewhere and you no longer have access to that device. Instead of waiting for the session to expire, or nuking the session store for all users, it would be great to have an API endpoint for `logoutAllSessions`. I believe it should be pretty easy to implement as well. Many thanks in advance.

**Comment by ViRb3** [comment]
In the short term, is there any way to (manually) do this at all? I took a look at the Redis store, but the session values appear to be in binary form (encrypted?). Thanks.

**Comment by james-d-elliott** [comment]
I agree this would be a nice addition. We're currently investigating the possibility in an upstream library and considering either hard forking it or making our own implementation. Currently the session library does not allow us to do this.

My technical proposal is ditching the library and writing it ourselves. It would require us to record a unique identifier for each user, and store that in redis/memory.

For example in redis:

key = ldap:CN=Example,OU=People,DC=example,DC=com
value = (session1, session2, etc)

**Comment by james-d-elliott** [comment]
> 
> 
> In the short term, is there any way to (manually) do this at all? I took a look at the Redis store, but the session values appear to be in binary form (encrypted?). Thanks.

Currently there isn't, I can look at what would be required and if it was possible. I might make a command that can manually do it depending on how difficult it is.

**Comment by james-d-elliott** [comment]
This will be rolled up into #1388 where we'll overhaul areas surrounding this. We'll reopen this issue it doesn't end up being part of the final design.

**Comment by jhalag** [comment]
A thought on this one as this has been waiting for a while. I was contemplating what I could do in order to "kill" a rogue OIDC session - as it can keep renewing itself via refresh tokens indefinitely. I don't think there is currently a way to do this - I believe it would even survive a password reset. Users should have a way to close that security hole if needed.

Trying to keep it simple, as an overarching "management interface" appears to be holding up this feature:

UI:
- Add a link to the basic Authelia landing page when you are logged in (mine currently has three links - logout / methods / 'lost your device?'). The new link would be "logout all sessions"

On the backend - it could either:
- store a timestamp in the user's record of the last time the "logout all" action was taken, and deny any token/cookie queries for tokens/cookies issued prior to that timestamp (simplest?)
- iterate all tokens/cookies in the store and revoke as appropriate

I didn't have time to dig into the codebase at the depth I'd like yet, so one or both backend approaches may not be entirely good fits. Wanted to get this suggestion out there though as it really seems like something that should be an option - even if it's just the big hammer ("log out everything"), we need a hammer sometimes.
