### ISSUE TITLE
Salt contains invalid base64 characters using /etc/shadow crypt 6 hashes

### ISSUE THREAD

**Issue by jdespraz** [authelia/authelia#2336]
### Description

In order to have a unique username and password for the users of my server, I configured Authelia to look into the /etc/shadow file to fill up the users.yml file with their {CRYPT}$6 passwords. Everything worked fine until a new user chose a password that resulted in a salt containing the character `.` which is not a supported Base64 symbol and as a result crashes Authelia.
Here's the resulting log:
```
panic: Unable to parse hash of user xxxx: Salt contains invalid base64 characters
```

### Expected Behaviour

Authelia accepts any character present in the /etc/shadow hashed passwords or provides a way to convert the hash to an acceptable format.

### Reproduction steps

Create a user on the machine that has a `.` symbol in their CRYPT 6 salt, e.g.
```
password: '{CRYPT}$6$AFKdKYjCTiSMq.C1$OnsgQhslR2kW1.C/fya55/iwL7bh1h8HSNnrNtR1JSl0vCOmb6iugDBZhVk/QbV59HV6tgXQLRNdi8QuWLwJV0'
```
the CRYPT hash of a user can be extracted with the command:
```
awk -F: '/username/ {printf "{CRYPT}%s\n",$2}' /etc/shadow
```

### Additional Information
The server runs on Ubuntu 18.04

**Comment by nightah** [comment]
This is because glibc's crypt function utilises `.` in [its base64 encoding](https://sourceware.org/git/?p=glibc.git;a=blob;f=crypt/crypt_util.c;h=c9cf9ba59e457656f2eace768c0083c490b44805;hb=refs/heads/master#l250) as opposed to what's defined as [true base64](https://en.wikipedia.org/wiki/Base64#Base64_table).

As far as I can see there's no way to specify/override what runes are randomly selected from for the Salt.

You could perhaps try and install [`libxcrypt`](https://launchpad.net/ubuntu/+source/libxcrypt) from what I can see this should hopefully work around the poor implementation issue and could resolve your issue.

**Comment by jdespraz** [comment]
Thanks a lot for the suggestion, it was quite hard to find clues online and it seems your workaround is the best.

To sum up, I did some tests after installing `libxcrypt` and creating new hashes. All the newly created salts contained only valid base64 characters. However, I still find it confusing since there seems to be no accepted standards that define which characters can be used in salts. According to libxcrypt's [documentation](https://www.mankier.com/5/crypt), it appears that any character except `$:\n` is allowed. They also explicitly state that 
```The common “base64” encoding specified by RFC 4648 is usually not used.```
I found an interesting discussion on [this issue](https://github.com/besser82/libxcrypt/issues/105) that discusses this problem in more details.

And just as a side note, for some reason, it seems (I did not test extensively) that in the original glibc implementation, salts with `.` characters only pop up when the original passwords have special characters in them (other than a-z,A-Z).

Should I close the issue or is glibc compatibility something that will be integrated in Authelia at some point?

**Comment by james-d-elliott** [comment]
I did some more reading last night.


> According to libxcrypt's [documentation](https://www.mankier.com/5/crypt), it appears that any character except `$:\n` is allowed. They also explicitly state that

This is rather interesting, since according to my research this is not true for the MCF standard or the PHC specification. Maybe it's so it's more compatible with everything?

> `The common “base64” encoding specified by RFC 4648 is usually not used.`
> I found an interesting discussion on [this issue](https://github.com/besser82/libxcrypt/issues/105) that discusses this problem in more details.

The difference is that's MCF we use the PHC specification. One key difference between them is that MCF has no specification document at all, it's just a "common standard", whereas the PHC does. I don't know about you, but considering there is a clear delimiter in the MCF it makes no sense to limit the characters like it does. Here is the PHC spec:

https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md

We chose this because at the time of implementing argon2 (and today) argon2 is considered one of the most secure algo's but it needed a method to define multiple parameters, which is where the `m=x,t=y,p=z ` becomes an issue because it's not supported by MCF due to the `=`'s.

So while they are correct when referring to MCF, they are not when it comes to the PHC spec.

> Should I close the issue or is glibc compatibility something that will be integrated in Authelia at some point?

I mean, did the passwords all match except the ones with the periods? If you can test this for us we can give you a definitive answer. I think we can probably continue to generate ours in the PHC standard but accept others if they still work. I'll discuss with the team.

**Comment by nightah** [comment]
> All the newly created salts contained only valid base64 characters. However, I still find it confusing since there seems to be no accepted standards that define which characters can be used in salts.

You can definitely hash passwords manually and likewise manually provide the salt, however similarly I could not find any way to override which characters the Salt could be drawn from.

There could be an alternative method to override the app/function called to generate the passwords but from what I could tell if that's available it's not easy to track down. libxcrypt very much does exactly what we're looking for plus with some of their developments it's likely that you'll have access to better hashing algo's (for example they have a WIP to implement all the argon2 variants). If I were you I would follow that up to see if the members/contributors are willing to help move that forward along with the author of the PR.

**Comment by jdespraz** [comment]
Thanks for the interesting discussion and the detailed explanation. I have to admit I'm not an expert at this and I am discovering those standards and conventions as I go through these issues.

@james-d-elliott 
> I mean, did the passwords all match except the ones with the periods? If you can test this for us we can give you a definitive answer. I think we can probably continue to generate ours in the PHC standard but accept others if they still work. I'll discuss with the team.

Yes this is what I observed, only the periods that popped up created the error and all other hashes were fine. It seems to me that what you suggest (accept some of the invalid characters when reading and follow strictly the standard when generating) is a good solution and that'd help me for sure with the implementation I've chosen here.

@nightah 
> You can definitely hash passwords manually and likewise manually provide the salt, however similarly I could not find any way to override which characters the Salt could be drawn from.

Yes but the idea was to have it done automatically and simply reuse the hash in authelia. I also wanted to have to do as little work as possible beforehand and not for instance change the way passwords are hashed in the system. So indeed, libxcrypt appears to be the easiest workaround, as you initially proposed. But if the developers are willing to change the way they read special "non-standard" characters that would be even better in my case.
