### ISSUE TITLE
Support for webauthn

### ISSUE THREAD

**Issue by tedstriker** [authelia/authelia#241]
It‘d be really nice to have support for the webauthn protocol.

**Comment by clems4ever** [comment]
Hello @tedstriker , this would indeed be a good idea! Thank you!
Do you already use Authelia without this feature?

**Comment by clems4ever** [comment]
Hello @tedstriker , do you already use Authelia? Also, do you have a concrete use case for webauthn with Authelia?

**Comment by naggie** [comment]
@clems4ever @tedstriker any further thoughts on this issue? I can think of some use cases:

* WebAuthn would unlock the use of more security hardware such as iPhone/Mac touch ID (I think) and various other fingerprint readers
* WebAuthn/FIDO2 support a (secure!) single-factor mode, which is convenient in some cases

**Comment by james-d-elliott** [comment]
Seems to be a wishlist item for the library we're currently using https://github.com/tstranex/u2f/issues/17

However https://github.com/duo-labs/webauthn seems to support it.

**Comment by Ornias1993** [comment]
I want to add to this:
Please make single-factor WebAuthn _optional_.

I don't want users to signin to websites using just a device I have no control over. I don't believe in that part of the WebAuthn standard. I don't think (for example) microsoft login is solid enough to use as sole an authentication device, which is (sadly enough) part of webauthn.

**Comment by andryyy** [comment]
How do you have more control over a username and password combination? You can still exclude WebAuthn client ids from logging in.

I also doubt a Yubikey (for example) is less secure. Just checkout the standard and how it works. There is no master key or something like that. :)

**Comment by Ornias1993** [comment]
Simple: I want to have the control to setup two factors, regardless of what webauthn thinks is safer.

I didnt say username and pass gives more control. I said I myself wants the control to only use webauthn as a second factor.

I never said yubikey is less secure. I said i dont believe system login (OS) is secure enough.

**Comment by james-d-elliott** [comment]
Authelia has always maintained a security-first approach to defaults, attempting to force admins to make an informed choice to reduce security. As such it is extremely unlikely that at any stage we will implement either an authentication protocol in a way which reduces current levels of security. 

My guess (and personal preference) based on previous experiences with the other team members is if we allow 1FA via Webauthn we would add a configuration section to decide which 1FA methods are allowed. This would very likely default to existing behavior.

That being said I think implementing Webauthn 1FA would be a complication to the flow of Authelia and it's likely the initial implementation of Webauthn in Authelia will only be a 2FA option in order to update to a protocol supported into the future. We should heavily consider the idea of Webauthn 1FA however as part of any initial design regardless. I imagine the storage back-end will have to be designed in a specific way to facilitate it in the future, and it makes a lot of sense to design that from the start.

**Comment by Ornias1993** [comment]
@james-d-elliott I think we are in full agreement on that one. While I have personal preferences on not using 1FA webauthn, I 100% support the idea of writhing future-proof code to support it in the future for users that do want to use it.

**Comment by james-d-elliott** [comment]
So just further thought regarding this and 1FA Webauthn due to discussing it in Matrix. I believe the most ideal solution if it's technically possible is this:

1. Configuration option (default off) to enable Webauthn as a 1FA option.
2. When a user visits a one_factor site, they can either use username and password or Webauthn to authenticate.
  - We record they provided either "something you know" or "something you have" depending on the choice they make.
3. User is redirected.
4. User visits a two_factor site they are redirected again.
  1. If they provided a "something you know" they are prompted for a "something you have" like TOTP, Webauthn, or Duo Push.
  2. If they provided a "something you have" they are prompted for a "something you know" like a username and password.

**Comment by andryyy** [comment]
Hm, just to add to the discussion: Is Webauthn with UV flag really that bad?

I mean, you have a single authentication process that includes two factors. You need the device and you need to verify it's you. 

I am not talking about the user presence flag, which would obviously not add anything to the security. User verification is mostly a PIN or your fingerprint. So you need the device plus ("have something") and verify it's you ("something you know"). :)

**Comment by james-d-elliott** [comment]
> 
> 
> Hm, just to add to the discussion: Is Webauthn with UV flag really that bad?
> 
> I mean, you have a single authentication process that includes two factors. You need the device and you need to verify it's you.
> 
> I am not talking about the user presence flag, which would obviously not add anything to the security. User verification is mostly a PIN or your fingerprint. So you need the device plus ("have something") and verify it's you ("something you know"). :)

I don't think it's inherently bad, just feel the admin needs to make an informed choice about their configuration. Several popular sites implementing Webauthn that I've seen currently implement it as only second factor after providing a username and password (Cloudflare being the most well known); even though they use UV flag as well.

We could realistically add additional policy configurations down the line, as things get more feature rich and complicated. Thinking about it, it may be nice to have user defined policies in addition to the standard 4. Or maybe an option to decide how to treat Webauthn specifically.

**Comment by Ornias1993** [comment]
> So you need the device ("have something") and verify it's you ("something you know"). :)

My personal grievence with this idea is that it's not true.
you need the device "something you have", which decides if it's you "something you know".

Which means: If that closed source NSA-backed codeblob gets compromised (which it already is known to be), it's in theory perfectly possible to just use the "something you have" and bypass the "something you know".

Webauthn 1FA is possibly safer against criminal attackers. but its designed to be less secure against Nation State attackers, which have been lobbying for precisely these bypasses against passwords for decades now.

**Comment by jwilleke** [comment]
WebAuthn is more secure the 2FA.
Read: <https://webauthn.guide/>
Uses a single public-private key and often has to be or can be unlocked with a passphrase for a TPM device.

- Impossible to use same credentials at more than one site.
- Impossible to forge or phish credentials. >70% of comprised credentials come from some form of phishing.

if someone got your authenticator device they then need to know which websites you used.

-jim

**Comment by james-d-elliott** [comment]
I've taken this task up for the next release. Today marks the first time I was able to get the appid extension to work. This will mean that previously configured U2F/FIDO/CTAP devices will work with the webauthn implementation we go with. You can consider this a request for comment.

In addition we will be have the following defaults as part of the initial implementation (unsure which ones we'll allow to be configured initially, but it's unlikely to be all of them):

|Setting                  |Value         |Effect                                                                           |
|:-----------------------:|:------------:|:-------------------------------------------------------------------------------:|
|Conveyancing Preference  |indirect      |We will ask users to permit collection of the AAGUID, this is like a model number|
|User Verification        |preferred     |We will ask the browser to prompt for consent to use the device                  |
|Resident Key             |false         |We will not allow passwordless login                                             |
|Authenticator Attachment |cross-platform|We will support security keys to start with, not platform authenticators         |

**Comment by igufi** [comment]
The defaults seem fine but I do want to cast my vote for the Resident Key to be supported - it is something I've been looking forward to for a long time.

**Comment by tomtastic** [comment]
Seconded, Resident Key and password-less logins are highly desirable for me.

**Comment by james-d-elliott** [comment]
I can't say for certain, but my personal opinion is we will eventually support an off by default passwordless login via resident keys. I think mostly we have to figure out what is possible with resident keys and what form we'd like it to take. I think for certain the conveyancing preference will be direct for passwordless login, and the user verification will be required.

**Comment by james-d-elliott** [comment]
The test branch is up, it works however it's not at all finished. I'm copy pasting the disclaimer here:

_**Warning:** using this branch in production may damage your database. Key point is the current schema is NOT the expected final schema and while there will be a schema migration path from v1 to v2, the current schema in this branch is NOT v2 final, and there will not be a migration path from the current v2, to the final v2. Use this branch **at your own risk**, we strongly urge anyone doing so to backup their database._ 

As you can also see there is quite a list of tasks to go, and it will remain a draft until then. But it should not take too long before the branch will begin going through the review process. Everything is subject to change upon peer review as well.

**Comment by saua** [comment]
Apparently the currently used U2F API is going to be deprecated in Chrome: https://developer.chrome.com/blog/deps-rems-95/ which AFAIK means the current U2F implementation will eventually stop working on Chrome (in late June 2022, please correct me if I misunderstood something and that's not actually what this means).

Does this influence the priority/urgency of this ticket (which I understand to be about implementing the future-proof alternative) or is there some in-between workaround (such as supporting only the existing use cases, but using the new APIs) that should be put into a separate issue?

**Comment by Ornias1993** [comment]
> Apparently the currently used U2F API is going to be deprecated in Chrome: https://developer.chrome.com/blog/deps-rems-95/ which AFAIK means the current U2F implementation will eventually stop working on Chrome (in late June 2022, please correct me if I misunderstood something and that's not actually what this means).
> 
> Does this influence the priority/urgency of this ticket (which I understand to be about implementing the future-proof alternative) or is there some in-between workaround (such as supporting only the existing use cases, but using the new APIs) that should be put into a separate issue?

It's already has both a testing branch **and** active development.
There is not more priority you can reasonbly ask from people doing this for free, unless it's a high or crit CVE.

**Comment by james-d-elliott** [comment]
In addition to above, it's very likely to be in the next release, and that is our intention. In addition the changes unfortunately forced us re-prioritize this already.

**Comment by saua** [comment]
Sorry, I didn't mean to be pushy, I just didn't notice that there was already a branch for this topic and the topic looked a bit untouched in an otherwise very active project. My fault for not noticing the ongoing progress!

**Comment by james-d-elliott** [comment]
Passwordless is being moved to #2827 as we're getting ready to release initial support for webauthn (it will be in the next release cycle).

**Comment by Ornias1993** [comment]
> Passwordless is being moved to #2827 as we're getting ready to release initial support for webauthn which will close this issue (it will be in the next release cycle).

Just a quick question, this time there are not going to be any breaking changes in the minor release?

**Comment by tibbe** [comment]
Will multiple security keys for a single user be supported? (It's more or less a must because users really should have at least one backup security key if they lose their primary one).

**Comment by Ornias1993** [comment]
> Will multiple security keys for a single user be supported? (It's more or less a must because users really should have at least one backup security key if they lose their primary one).

Yes, this is really a must and one of the flaws in some websites! 👍

**Comment by james-d-elliott** [comment]
> > Passwordless is being moved to #2827 as we're getting ready to release initial support for webauthn which will close this issue (it will be in the next release cycle).
> 
> Just a quick question, this time there are not going to be any breaking changes in the minor release?

We will be removing the ability to register U2F devices at least until a point someone can provide compelling reason why we'd support this. All registered devices will require FIDO2 Webauthn support. Considering a major browser is removing  support for them anyway via a unilateral decision similar to the ActiveX days, I doubt this will be an issue. Otherwise there are no planned breaking changes.

> Will multiple security keys for a single user be supported? (It's more or less a must because users really should have at least one backup security key if they lose their primary one).

This is definitely something we considered in the implementation. The implementation contains the necessary tooling in the backend to make this happen as it is a necessary feature in my opinion. A single user can have multiple tokens as long as the descriptions vary which  will be an element users can define when registering a key.

However currently the frontend does not allow it.  It's something we'll have to add  and I plan to prioritize this for my own reasons. The importance of getting webauthn itself implemented far outweighed this, and the change is already insanely large. Doing these features separately is going to facilitate an implementation with less bugs  and probably less time than if it was done all at once.

I would really like to at some stage implement a feature whereby a user registers an emergency device which is registered and linked to another key, if ever used will immediately disable linked devices from being used. That'll just take some fancy UI work which I loathe!

**Comment by joshxyzhimself** [comment]
Can webauthn be first-factor now?

https://www.authelia.com/docs/features/first-factor.html says:

> IMPORTANT: This is currently the only method available as first factor. Using other methods will likely be possible when [WebAuthN](https://github.com/authelia/authelia/issues/241) is implemented

**Comment by james-d-elliott** [comment]
No. See #2827

**Comment by aguilaair** [comment]
Hey, does the current implementation support fingerpring/face id as a valid webauthn verification method? I keep getting prompted for a security key.

**Comment by james-d-elliott** [comment]
It only supports cross-platform authentication. i.e. ones you can move between systems at this stage. It's likely after we add the UI for multiple devices, then discoverable credentials (passwordless) that the ability to allow users to add platform authentication will be added. These authenticators are generally more complex and we wanted to gradually introduce parts of webauthn to test them in advance as best as possible.

Feel free to open a FR to track the feature though and prevent us forgetting. Though it is an item on the new roadmap which will be published soon.

**Comment by mroffbeat** [comment]
Here is something i found out, i got the prompt for a security key also, instead of TouchID or Face ID. 
While tweaking around i found a SOLUTION!!!

PROBLEM: Authelia will not generate a QR Code for the iphone to scan and add passkey to keychain. It will prompt you for a hardware-key 

SOLLUTION: access auth.example.com on an ANDROID phone, it will generate a QR CODE. 
Scan the QR code with the iphone. Voila.. done.. Touch ID / Face ID now works.. 

How silly is this?
