### ISSUE TITLE
Misleading used/expired 2FA registration token error

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2449]
## Bug Report

User clicks on the "Register" button in the 2FA registration mail repeatedly. Looks like token gets used and subsequent attempts are erroneous. User is shown "Failed to generate the code to register your device"

Instead relevant error message should be shown a'la "The provided link has been used or is expired, please resend the mail"

**Comment by nightah** [comment]
The message is quite generic on purpose to avoid leaking any information to a potential attacker.

I think the best way to address this would be to modify the email template which is sent to the user to notify that each email/token can only be used once as they self-destruct on initial click/usage.

**Comment by laurivosandi** [comment]
Then the message should list all the possible causes for failure. Current message results in helldesk overload

**Comment by laurivosandi** [comment]
Also current error looks like client (JS/browser) side error

**Comment by nightah** [comment]
As I mentioned these are intentional measures along with other design decisions to ensure that information isn't leaked to an attacker.

Providing additional information in failure scenarios can allow an attacker to perform enumeration type attacks.

We will reconsider this specific scenario with the team and update accordingly with our decision moving forward, though, in my eyes the simple fix would be to add a notification regarding the tokens/links in the actual email template.

**Comment by laurivosandi** [comment]
If the error message lists all possible reasons then no meaningful information is leaked to attacker -- however it helps real user to understand what could have gone wrong....
