### ISSUE TITLE
Having secrets throws errors even if those are not called in the config

### ISSUE THREAD

**Issue by Bockiii** [authelia/authelia#2506]
### Description

If you have defined a secret (e.g "authelia_notifier_smtp_password") through the environment variables, but are not using it in the configuration, you will get an error message.

For the notification example:
- Define a file notification in your configuration and start authelia. It's going to work.
- Set the "authelia_notifier_smtp_password" environment variable to something
- Start authelia again

### Expected Behaviour

Authelia starts just as before with a file notification setup.

### Actual Behaviour

Authelia throws an error message claiming to "only define one notification handler in the configuration"

### Additional Information

This worked "before" (aka I did an update on my :latest container and suddenly everything was throwing errors) and must have changed within the last few months.

It happens at least for the notification and the "authelia_storage_mysql_password" secret (it then throws the error message to define an SQL host and user).

So, in order to solve this, Authelia should ignore environment variables that are not used in the configuration.

**Comment by james-d-elliott** [comment]
Hi @Bockiii. This is not a bug with Authelia it was an intended change. In order to support the ability to use environment variables as configuration it is necessary.

You just need to update the configuration appropriately to not have environment variables you're not using, just as you would not configure the DUO section if you were not using it.
