### ISSUE TITLE
Question : Authelia vs broken loopback & dynamic IP

### ISSUE THREAD

**Issue by hot22shot** [authelia/authelia#2608]
Hi,

I'm using Authelia behind npm and it works great, nice job.

I only have one small issue which is not caused by Authelia but is due to my ISP.
The loopback on my network is not working, that means when using a DNS redirection handled by my reverse proxy inside my network I'm seen by Authelia with my public @IP and not with my private @IP.

Obviously I would like to bypass Authelia when accessing my services from inside my network, to do that I added my public IP in Authelia configuration file.
But it only works for a while because I have a dynamic public IP, so when my ISP decide to change my public IP Authelia fall back to the authentification it applies to an external IP (as it should).

So my question is : do you know of a way this could be automated so I don't have to edit Authelia's configuration file and restart it each time my public IP is changing ?

Have a nice day

**Comment by nightah** [comment]
You could get around the issue by running [split horizon DNS](https://en.wikipedia.org/wiki/Split-horizon_DNS).

Effectively anytime you go to any of your domains that are hosted internally on your network those addresses route to the internal IP address of your server as opposed to going via the NAT Hairpin of your router.

You could potentially do this at your router (if it allows you to configure DNS), otherwise if you run any DNS sink-hole/ad-blocking software like Pi-Hole, AdGuard Home, Dnsmasq etc you could do it there.

**Comment by hot22shot** [comment]
Good idea thank you !

I was able to do it with my AdGuard Home container, more specifically with a DNS rewrite where I redirected my local domain to the private IP of my unraid server.
