### ISSUE TITLE
Passwordless authentication

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2783]
## Feature Request

I would like to see option of dropping passwords altogether in our deployment. That is adding a method of logging in without password.

Basic rationale is that:
a) if user is not frequently using the system we would like to make sure that if their password leaks (from other services where they potentially use same password) the abusers can't penetrate our services
b) since password reset functionality already relies on the security of the mailbox, we could just omit the password reset step, send user just a login link and prevent potential abuse described above

### Description

1. User tries to access service
2. Authelia intercepts traffic
3. User is presented with Authelia login challenge
4. User types their e-mail address
5. User is e-mailed a single use token
6. User taps on the token in the e-mail
7. Authelia login challenge described in 3. proceeds to the application

Note that for example Slack is already using similar method https://www.waveguide.io/examples/entry/passwordless-login/

**Comment by clems4ever** [comment]
Hello @laurivosandi , thanks for this proposal.
Authelia is primarily made for two factor authentication. The scenario you describe is not really passwordless since the user needs to authenticate against the mailbox. Your proposal relates more to the fact the first and single factor you want would be to use an OTP sent to the email address of the user.

Unfortunately, this is not in our short term plans to support this feature and there is already an issue open for it: https://github.com/authelia/authelia/issues/2035. Please stay tuned on this one.
