### ISSUE TITLE
Can not build docker image

### ISSUE THREAD

**Issue by Shihta** [authelia/authelia#2843]
### Description

follow the document [Authelia Scripts](https://www.authelia.com/docs/contributing/authelia-scripts.html) and run the `authelia-scripts docker build`, but it doesn't work

![截圖 2022-02-02 下午8 25 20](https://user-images.githubusercontent.com/5186176/152154835-0c13c533-6c05-46d4-9491-19be7eff3c51.png)

### Expected Behaviour

it should build a docker image

### Reproduction Steps

1. `source bootstrap.sh`
2. `authelia-scripts docker build`

### Additional Information

_N/A_

**Comment by nightah** [comment]
Think this is just a documentation error since our build process has changed a little bit.

Can you please try the following command: `authelia-scripts docker build --container=dev`?

**Comment by nightah** [comment]
Okay so I can see what the issue is here and we'll fix the problem in our `bootstrap.sh`.

To be able to utilise `dockerignore` files for specific Dockerfile's (like our `Dockerfile.dev.dockerignore` you need to be using a Buildkit Backend.

You can get around this for now by just running `DOCKER_BUILDKIT=1 authelia-scripts docker build`.

I'll put a PR up shortly fixing the problem.

**Comment by Shihta** [comment]
Thanks for your clarification, my docker version is 20.10.12 and I'll study the BuildKit.

But even enable the BuildKit builds, there is still an error in the `Dockerfile.dev`:

![截圖 2022-02-03 下午2 26 21](https://user-images.githubusercontent.com/5186176/152292347-400e7268-ccc6-427c-8f51-bd9178ee0cab.png)

I guess it still needs a adjustment like [this](https://github.com/authelia/authelia/pull/2844/files#diff-86930c95a19b82f7e64a962a0053d44e855824813019b3698eae4917a90cdcacL58)?
