### ISSUE TITLE
Remember preferred MFA method per browser

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2865]
Currently it seems preferred multifactor authentication (U2F vs TOTP) method is stored on server side. As I am using TOTP on phone and U2F on laptop I have to switch very frequently.

Instead last used method could be stored on browser (eg [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) or similar)

**Comment by james-d-elliott** [comment]
I think really the issue is the preferences are stored per-user, not that they're stored on the server. 

We have two options for this:
- We can realistically utilize localStorage for this. We'd have to investigate the downsides, one that I can think of is the data could theoretically be more easily changed by outside parties. This may open the localStoage to being more vulnerable than the other option.
- We can realistically have per-device tracking with a long lived cookie (additional to the session cookie) that frequently is updated. The added advantage of this cookie is it can be utilized in the future to track "known" clients, which could allow us to add some logic that would do additional verification/less verification steps to devices which the user is known to have used in the past. The cookie would operate the same as the session cookie but it would just have a different name and random value.

Few roadblocks to this:

- user consent dialogue (GDPR compliance, and I think PCI compliance) (localStorage/cookie)
- session library is just not suitable for this at this time (cookie)

**Comment by james-d-elliott** [comment]
Closed discuss in #1699
