### ISSUE TITLE
Document Traefik externalTrafficPolicy should be set to Local

### ISSUE THREAD

**Issue by ybizeul** [authelia/authelia#2882]
I've been banging my head all day on this, I think it would be useful to document.

If Traefik LB service doesn't have the `externalTrafficPolicy` set to `Local`, Authelia will get worker node IP address as the source IP, which makes it impossible to rule on `networks`.

With Helm Traefik deployment, one should set the following in values file :

```
service:
  annotations: 
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
```

Otherwise, simply add :
```
  externalTrafficPolicy: Local
```

In Traefik LoadBalancer Service

**Comment by james-d-elliott** [comment]
Actually the situation is if it's not set it's traefik that gets the node IP in some circumstances (depends on how you've configured everything). It just forwards that incorrect IP it to Authelia. This occurs with several exceptions. I think there is potential for us to document this however I feel it's rather difficult since this can apply to all k8s ingresses and it's really the responsibility of k8s and these ingress providers to document this part as [k8s has done here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) and traefik has seemingly had long term resistance to documenting it.

**Comment by ybizeul** [comment]
You’re totally right, its not Authelia responsibility. I see the Kubernetes deployment documentation is under construction, with an nginx proxy example. A full Traefik sample would be beneficial. Maybe I can whip up something and contribute to k8s documentation section.

**Comment by james-d-elliott** [comment]
I think as long as we make sure there is a link to that doc in the general k8s docs then that may suffice, thoughts? It's applicable regardless of ingress and is really now that I think of it more of k8s networking issue which may explain traefik's stance. It did get documented in v1 but they removed it again in v2 and there is basically no mention in their helm chart, which is even more baffling.

But yes in general a full traefik k8s example would be nice. Particularly if the generic parts could be made thus and the traefik specific parts be on their own. Adding duplicate docs for each ingress isn't a nice thing to maintain.
