### ISSUE TITLE
Blocked iFrame for CryptoTokenExtension showing in Chrome v98.0

### ISSUE THREAD

**Issue by michaelkrieger** [authelia/authelia#2920]
## Bug Report
Authelia v4.33.2

### Description
Displaying a blocked Chrome extension (CryptoTokenExtension) box in the bottom corner that it never used to.

![2022-02-27 (1)](https://user-images.githubusercontent.com/7321259/155894093-d1f6c4fe-cea1-498e-af86-5029855fef54.png).

The Javascript console displays these errors:

- vendor.e43a5c96.js:582 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-c2WQZE7QQcRLxDz0HmUsyE7shVEUWjMy'". Either the 'unsafe-inline' keyword, a hash ('sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
z.getIframePort_ @ vendor.e43a5c96.js:582
- Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null'). @ vendor.e43a5c96.js:582
- U2F not supported (anonymous) @ index.b4ae602a.js:1

### Expected Behaviour

This box should be hidden or the underlying error fixed.

### Reproduction Steps

1. Set up a user with 2FA with a OTP.
2. Login using username and password, checking 'remember me'
3. See invalid iframe.

### Additional Information

_N/A_

**Comment by james-d-elliott** [comment]
This is actually Chrome deprecating U2F which is resolved by #241 which will be implemented by #2707, alternatively you can re-enable the chrome U2F APi. If you feel this is a bug report it to Chrome as it is Chrome injecting foreign scripts into webpages to communicate with users rather than displaying a browser dialgoue. 

We disallow foreign scripts from being used with Authelia as a security feature. You're welcome to disable this by removing the Content-Security-Policy header. However this would allow any plugin to potentially steal credentials.

**Comment by michaelkrieger** [comment]
I much prefer this behaviours and have no need to U2F.  Certainly don't love Chrome nor their way of doing anything.

Thank you for taking a peek at it.  Wasn't aware of the WebAuthN changes coming. Just wanted to make sure Authelia isn't relying on something that's disappearing and it sounds like all is well.

Thanks again.  Closed.
