### ISSUE TITLE
iOS: Webauthn gesture detection.

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#2970]
### Description
As per this comment https://github.com/authelia/authelia/issues/2962#issuecomment-1059923478 iOS requires a user input to begin webauthn. We need to add detection for this. We will need to detect this error ad alter the component to render a "Start Webauthn Login" / "Start Webauthn Registration" button when this error is detected.

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

_N/A_

**Comment by james-d-elliott** [comment]
Additional information: https://github.com/w3c/webauthn/issues/1293

**Comment by james-d-elliott** [comment]
@werty1st can you confirm if you see this when using a browser on iOS that isn't Safari?

**Comment by james-d-elliott** [comment]
Can you please try the authelia/authelia:[fix-ios-webauthn](https://github.com/authelia/authelia/tree/fix-ios-webauthn) image tag as well, pretty sure that'll fix the authentication step (will require a user to click start if on iOS/Safari). If it does I'll apply the same thing to the registration site.

**Comment by werty1st** [comment]
I can trigger the native dialog but then nothing happens. i also tried to register a new device but that doesnt work either.
Can you make it more verbose? i dont see any message in the safari logs. could you build the debug image without minified javascript?

**Comment by james-d-elliott** [comment]
As I said, once I get the fix right for auth I'll get it resolved for registration. What do you mean nothing happens after the native dialogue? 

I've never built a react frontend like that, I can try though as long as you're comfortable replacing or running the authelia binary manually.

**Comment by werty1st** [comment]
I'm willing to help debugging. I tried to setup a dev env but i couldn't figure out how to run the JS/TS code without minification.

**Comment by werty1st** [comment]
> As I said, once I get the fix right for auth I'll get it resolved for registration. What do you mean nothing happens after the native dialogue? It should either allow you to auth. show an error in the dialogue, show a notification toast, or show a notification toast and log a web console error.

iOS opens the nativ overlay that tells me to bring the NFC Stick near the phone. The phone recognizes the NFC Tag but the webauth dialog doesn't go away.

**Comment by hendrik1120** [comment]
Hi, I noticed this issue too. "You cancelled the assertion request" pops up imediatly after logging in with the password. But after clicking "retry" the verification works as normal. Tested this on Safari on iOS and macOS with latest updates.

**Comment by james-d-elliott** [comment]
Probably something wrong in my logic, I'll double check it.At least we know we're on the right track.

**Comment by hendrik1120** [comment]
@james-d-elliott I only tested the standard build. I am using a YubiKey aswell but I can just click the "Retry" button and it works instantly after that.

**Comment by james-d-elliott** [comment]
Yep that's expected, Apple has special requirements that are not part of the spec or required by any other vendor that the user makes a direct interaction with the site that causes the process to start. Can you try my test build to see if you get similar results with login?

**Comment by hendrik1120** [comment]
Ok, so I just quickly dropped in the docker container from the test branch and I now get the message to basically press the button, so apple is happy on Safari (iOS). On macOS however, I still get the same error as I mentioned earlier and then need to press "Retry".
[Screenshot Safari iOS](https://user-images.githubusercontent.com/89412959/157122577-8c813c12-4806-4be4-a508-cd7b1e4e3fd9.jpeg)
[Screenshot Safari macOS](https://user-images.githubusercontent.com/89412959/157123718-6f95a2f3-263e-4d94-a639-4ac3dd8ff310.png)
If u need any logs, just let me know.

**Comment by james-d-elliott** [comment]
Might be a detection issue. Can you confirm it doesn't show the start button?

**Comment by hendrik1120** [comment]
Yes, on macOS and ipadOS I never saw the start button

**Comment by james-d-elliott** [comment]
I'll update the detection rule. Does the auth work.after clicking retry.for you,?

**Comment by hendrik1120** [comment]
Yes, the auth works on all of my devices.

**Comment by james-d-elliott** [comment]
I think I fixed the detection rules on both auth (tested) and registration (untested) on the test build.

**Comment by hendrik1120** [comment]
Auth works great now. Except for a minor issue where "Something went wrong, ... " is displayed while being redirected after successfully authentication.
I tested the registration on macOS as well. I had to get a new link after the first attempt failed with the same error "You cancelled the assertion request" the second attempt worked fine after that.
I did some more testing after that and now I dont even get the macOS pop-up after clicking the start button for the registration. I used the same key for the test accounts, maybe its because of that.

**Comment by james-d-elliott** [comment]
There should be a log message if a duplicate key is an issue, I'll take a quick look at what could cause what you're experiencing regarding registration.

Regarding login that sounds like a double scan to me, can you confirm if you hear an audible  feedback, and if you do, do you hear it once or twice?

**Comment by hendrik1120** [comment]
I don't hear any audible feedback, but I just noticed that I need to touch the key twice every time.

**Comment by james-d-elliott** [comment]
Could you elaborate regarding touching the device twice? Is it once before the PIN and once after and is it entirely on the native UI? if so that's an implementation decision by Apple and we have no control over it. You can decide to not require user verification as it's a configuration option.

Also can you ensure you pull the latest image and still experience the registration issues? I'm nearly certain it's fixed.

**Comment by hendrik1120** [comment]
My Yubikey doesn't have a pin setup, so I get the native prompt instantly. Apple also doesn't enforce touching the key twice, as it works on other Webauthn sites with just one. 
I don't know how you implemented the start authentication button, but it now pops up in Chrome for macOS which doesn't require a user input before using Webauthn like Safari does.

I would suggest spinning up a macOS VM or something to see the issues for yourself, as I don't get any information in the logs and can't help except describing the issues.

**Comment by james-d-elliott** [comment]
> My Yubikey doesn't have a pin setup, so I get the native prompt instantly.

The PIN is part of the native dialogue. Also we request a PIN is setup as part of the registration process with default settings. In which case if you were never prompted, then it's a U2F key not a Webauthn key, so you can't really compare the flow to native Webauthn as the protocol does operate differently on nearly every device when using U2F compatibility mode.

> My Yubikey doesn't have a pin setup, so I get the native prompt instantly. Apple also doesn't enforce touching the key twice, as it works on other Webauthn sites with just one.

I think it's a bit strange you're making this statement when you don't have a PIN setup at all. The situation observed is that when you have a PIN it waits for you to NFC scan it again after you enter your PIN. Also this is all in the native dialogue, and the dialogue is not entirely informative about what you need to do in this instance; which we have no control over.

> I don't know how you implemented the start authentication button, but it now pops up in Chrome for macOS which doesn't require a user input before using Webauthn like Safari does.

The method we utilized to detect Apple and provide the Apple specific start button was utilizing a library to detect the OS/Browser/etc. If you'd like we can add some console logs of what information is detected that way we can figure out why it's not identifying your device. See the library site to see all of the huge orgs using it:https://faisalman.github.io/ua-parser-js/

> I would suggest spinning up a macOS VM or something to see the issues for yourself, as I don't get any information in the logs and can't help except trying to describe the issues.

Sadly you cannot legally run a macOS VM on anything other than a Mac. Apple make support for their system harder than Microsoft, with a stricter license agreement which prevents running their OS on VM's entirely if not on a Mac. So we're going to need involvement from people having the issue to solve it, or Apple need to fix their implementation to not operate differently to every other one in existence.

**Comment by james-d-elliott** [comment]
Note I added those web console logs.

**Comment by hendrik1120** [comment]
Ok, thanks for all the information.

I assume with PIN you mean the account password in macOS right?
Since I never had to put in any PIN or password in any form using webauthn on macOS or iOS I didnt think of that.

I also purged my whole authelia installation except for the config files. All databases dropped.
I am using FreeIPA in a VM and authelia, redis, mariadb docker containers just fyi.

After that I tried registering my Yubikey 5C NFC again in Safari on macOS.

Device Info from Safari: 
[Log] device.vendor:  – undefined (index.e3e33542.js, line 1)
[Log] device.model:  – undefined (index.e3e33542.js, line 1)
[Log] device.type:  – undefined (index.e3e33542.js, line 1)
[Log] cpu.architecture:  – undefined (index.e3e33542.js, line 1)
[Log] os.name:  – "Mac OS" (index.e3e33542.js, line 1)
[Log] os.version:  – "10.15.7" (index.e3e33542.js, line 1)
[Log] browser.name:  – "15.3" (index.e3e33542.js, line 1)
[Log] browser.version:  – "15.3" (index.e3e33542.js, line 1)
[Log] engine.name:  – "WebKit" (index.e3e33542.js, line 1)
[Log] engine.version:  – "605.1.15" (index.e3e33542.js, line 1)
[Log] apple:  – true (index.e3e33542.js, line 1)

Device Info from Chrome for macoS:
device.vendor:  undefined
index.e3e33542.js:1 device.model:  undefined
index.e3e33542.js:1 device.type:  undefined
index.e3e33542.js:1 cpu.architecture:  undefined
index.e3e33542.js:1 os.name:  Mac OS
index.e3e33542.js:1 os.version:  10.15.7
index.e3e33542.js:1 browser.name:  99.0.4844.51
index.e3e33542.js:1 browser.version:  99.0.4844.51
index.e3e33542.js:1 engine.name:  Blink
index.e3e33542.js:1 engine.version:  99.0.4844.51
index.e3e33542.js:1 apple:  true

My device is also running the M1 arm64 chip if that makes a difference.

I was able to register the key, but nothing really changed. Is it possible that the key still gets registered as U2F and not Webauthn? The docker logs however show: 
time="2022-03-11T02:43:39+01:00" level=debug msg="Mark 1FA authentication attempt made by user 'hendrik'" method=POST path=/api/firstfactor remote_ip=172.18.0.1
time="2022-03-11T02:43:39+01:00" level=debug msg="Successful 1FA authentication attempt made by user 'hendrik'" method=POST path=/api/firstfactor remote_ip=172.18.0.1
time="2022-03-11T02:43:43+01:00" level=debug msg="Save new preferred 2FA method of user hendrik to webauthn" method=POST path=/api/user/info/2fa_method remote_ip=172.18.0.1

**Comment by james-d-elliott** [comment]
> My device is also running the M1 arm64 chip if that makes a difference.

It shouldn't, and that indicates we're detecting it correctly, how odd that Chrome is acting different.

> I was able to register the key, but nothing really changed. Is it possible that the key still gets registered as U2F and not Webauthn? The docker logs however show:

It's not, though maybe it's possible we record it wrong. From what I can tell from the logs the registration failed. Can you confirm that the details in the DB have changed/not changed? If you register the kid should change and attestation_type should not be fido-u2f.

**Comment by hendrik1120** [comment]
I used the lost your device function to re-register the key and the kid,id changed in the db. The attestation_type is "packed" and transport is "usb, nfc" if I use Chrome. With Safari, the attastation_type is the same, but transport is just blank.
Same error in the docker logs as above.
>level=error msg="the token has already been consumed" method=POST

**Comment by hendrik1120** [comment]
With the latest release of iOS 15.4 and macOS 12.3 apple has changed their native webauthn dialog and removed the requirement for user input. Instead, you now get prompted by Safari whether you want to grant access to your security keys.
I only noticed this because I have cloudflare setup with 2FA and got the new native dialog. (so no official apple sources) I logged into cloudflare multiple times without having to click on anything after allowing the site once in Safari.

The authelia main branch now works fine for me without any errors. Registration works much better also and I havent noticed any issues so far. 
The native dialog however is different compared to the one I get from cloudflare and I also cant register touchID with authelia. This might have something to do with the missing multi key support in authelia.

@james-d-elliott  thanks for looking into this and your great work on authelia!

**Comment by james-d-elliott** [comment]
We have not implemented platform authenticators, specifically because  we want a more robust dialogue to be able to have users make informed choices about when to register these. Also I have an iPad now that should allow me to test the previous version of iOS since it's an older one. 

How is it different from the one from cloudflare? Should be noted there are numerous options webauthn allows services to specify, We took a more secure approach than most implementations I've seen use, specifically by default asking for conveyancing.

**Comment by hendrik1120** [comment]
> Also which version of Authelia? 4.34.4? Or the branch I made?

Release v4.34.4
> How is it different from the one from cloudflare?

Whops, it's actually just a different submenu. Safari automatically switches to touchID when registered. The "Other Sign In Options" button at the bottom brings up the same menu as for authelia. Sorry, my bad.
Cloudflare:

<img width="460" alt="Cloudflare" src="https://user-images.githubusercontent.com/89412959/158903961-37048cc3-e9b9-462b-8a0d-792fd6688aff.png">

Authelia:

<img width="463" alt="Authelia" src="https://user-images.githubusercontent.com/89412959/158903967-101d200b-fac7-4bc0-b1b1-09628b70d79f.png">

**Comment by james-d-elliott** [comment]
The fact that you no longer need to interact is really nice. Having to implement that change when webauthn has a presence requirement out of the box is asinine.

**Comment by james-d-elliott** [comment]
This has been fixed by Apple.

**Comment by manishsatschel** [comment]
In IOS safari browser when ever user closes the webauthen popup using the cross button. it does not appear again
