### ISSUE TITLE
Password reset links don't work when Outlook "safe links" are enabled

### ISSUE THREAD

**Issue by dakriy** [authelia/authelia#2994]
# Description

When going through the password reset process with an email service that provides link scanning (such as outlooks "safe links" feature), the password reset links do not work as they are designed to be single use. It appears in the case of "safe links" that "a preceding HTTP HEAD request with a User-Agent of Go-http-client/1.1, which we believe to be the safelinks service" is sent, according to a similar issue on fusion auth: https://github.com/FusionAuth/fusionauth-issues/issues/629.

Does Authelia invalidate password reset links on a head request? And follow up question, should it?

This is a very annoying issue as it makes password resetting impossible through Authelia in these situations

**Comment by james-d-elliott** [comment]
Yep this makes sense. We've been talking about this recently and feel moving to a emailed one time password that enables elevated actions for a period is probably the most modern solution to identity verification of this nature which should solve it. I know it wont be in the next release, may not be in the one after that, but shouldn't be far off.

**Comment by KevinGelking** [comment]
I'd like to chime in on this issue; I'm using v4.34.6 deployed as docker via Unraid and when a Password Reset email is sent to the user in question - no matter if outlook or google mail - a button is displayed which cannot be clicked, even when marking the E-Mail is marked as safe.

Currently that means that I have to give each user a password which they cannot set or change without a third party (an admin) knowing that password unless I feel like explaining how to hash it by themselves.

It'd be nice to have the Link displayed instead of a button (maybe that way users could at least copy it out if their inbox strikes);

**Comment by james-d-elliott** [comment]
We're adding the ability for admins to replace the email templates themselves in 4.35, and potentially the link though I think that can be left to admins who want to do that specifically.

**Comment by james-d-elliott** [comment]
See #3801
