### ISSUE TITLE
Support for mTLS

### ISSUE THREAD

**Issue by superadmin84** [authelia/authelia#3041]
Currently, the Authelia server config supports specifying a TLS certificate and key. Options to allow or require a client certificate, and to specify a CA certificate to verify the client certificate should be added. This enhances security by better identifying connecting clients or proxy servers.

**Comment by james-d-elliott** [comment]
This seems relatively niche, there are not many scenarios where this would actually improve security at all because Authelia is required to sit behind a reverse proxy. 

Can you share the use case including a brief summary of the network architecture that would demonstrate the benefit of this?

**Comment by clems4ever** [comment]
@james-d-elliott , I don't think this is so niche actually, it should be the recommended way to setup Authelia in the most secure way IMO. I think mutual authentication between LB and Authelia is important because it would prevent attacks from within the internal network (if not already protected with some kind of service mesh or network overlay with ACLs).

And by the way, mutual auth would also be the proper way to avoid the security limitations of X-Forwarded-User header which can easily be tampered with from within the network but this is another story because I think most backends don't support mTLS.
