### ISSUE TITLE
authelia hash-password throws error using special characters even with single quotes

### ISSUE THREAD

**Issue by HannesJo0139** [authelia/authelia#3434]
Hello,

I'm trying to hash a password using the command `docker run authelia/authelia:latest authelia hash-password '-Txyz' --config=./configuration.yml`.

Unfortunately, using single quotes somehow does not prevent the password from kind of being interpreted. Following error is thrown:
```
Error: unknown shorthand flag: 'T' in -T
Usage:
  authelia hash-password [password] [flags]
```

**Comment by james-d-elliott** [comment]
Anything not starting with `-` will work when quoted, I can make a fix to this however.

**Comment by HannesJo0139** [comment]
Yeah propably a very rare case. I just managed to hash it using `docker run authelia/authelia:latest authelia hash-password --config=./configuration.yml -- '-Txyz'`. Perhaps a corresponding hint in the doc would be nice.

**Comment by james-d-elliott** [comment]
> Yeah propably a very rare case. I just managed to hash it using `docker run authelia/authelia:latest authelia hash-password --config=./configuration.yml -- '-Txyz'`. Perhaps a corresponding hint in the doc would be nice.

Nice find. I was just going to make an optional `--password` flag which would work as well. However I can just change the docs (will just do the new docs instead of current ones) to instruct people to use `docker run authelia/authelia:latest authelia hash-password --config=./configuration.yml -- "<password>"`. Then if they always use that then it's never going to occur with this edge case.

**Comment by james-d-elliott** [comment]
@all-contributors please add @HannesJo0139 for docs
