### ISSUE TITLE
SSO with basic auth?

### ISSUE THREAD

**Issue by helmut72** [authelia/authelia#3498]
I use Caddy with Authelia and it works great!

But I have one question. I have configured 2 whoami instances:

```
	forward_auth authelia:9091 {
		uri /api/verify?rd=https://authelia.example.com
		copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
	}
```

and

```
	forward_auth authelia:9091 {
		uri /api/verify?auth=basic
		copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
	}

```

When I login on one instance I must login to the other instance again. Is no SSO possible, no matter if I use form auth or basic auth? Some webapps needs one or the other. It works when I use form auth or basic auth on both.

Thank you!

**Comment by helmut72** [comment]
Is this a normal or expected behavior or do I need some configuration or is this an error?

**Comment by james-d-elliott** [comment]
It's been a long time since I've looked at the setting, my recollection is it forces the use of the Authorization header or returns the WWW-Authenticate header if it isn't present and is not affected by sessions. You can still use the Proxy-Authorization header the same way without `?auth=basic` for reference, and most proxies allow you to rewrite a Authorization header to a Proxy-Authorization header.

I'll take a look at this as soon as I can to give you something definitive.

**Comment by helmut72** [comment]
Ok, thanks!

**Comment by james-d-elliott** [comment]
The implementation requires the header for each request. Users who don't want to do it this way can utilize the session cookies (the API can be used by machinery for example).

**Comment by helmut72** [comment]
> can utilize the session cookies (the API can be used by machinery for example).

Thanks for the info at all, but I don't understand what you mean with this.

**Comment by james-d-elliott** [comment]
There is an API which is documented at the `/api/` path of your authelia instance, it describes the authentication/etc API. You can retrieve the `Set-Cookie` headers returned by that to send the `Cookie` header which will allow SSO.

**Comment by helmut72** [comment]
Thanks, will look into it.
