### ISSUE TITLE
Wait longer for redis connection during startup

### ISSUE THREAD

**Issue by laur89** [authelia/authelia#3677]
## Feature Request

Would be nice to make Authelia wait for Redis availability at startup for a configured amount of time, including indefinitely. 

### Use Case

For my personal home-server, I'm managing containers using [unraid](https://unraid.net/) OS and its docker container management is extremely primitive. Because I allow both redis & authelia images to be auto-updated, then there are cases where both are updated simultaneously, and when Authelia update is completed before Redis, then former fails to start up.
Grace period for Redis availability should help with this case.

Running `v4.36.2` in a container.

**Comment by james-d-elliott** [comment]
Without log output it's a bit hard to see what would actually solve your issue. 

Theoretically the restart policy `unless-stopped` should solve it without adding a complex feature (which we're not going to do I don't think) in the instance of no route to host or DNS lookup issues, if the issue is a TCP timeout then allowing customization of that may also be a solution which we're willing to allow as it's supported in many other areas and supported by the redis library; though the restart policy would also fix it. 

However the timeout adjustment would theoretically only work if the IP of redis doesn't change between container restarts. If the IP is resolved by Authelia as 172.16.0.28, and redis restarts as IP 172.16.0.45 there is a high chance the only solution will be the restart policy and adjusting the TCP timeout will only make the situation worse for you.

**Comment by laur89** [comment]
`unless-stopped` is an obvious solution I failed to think of, thanks. Closing for now - if that won't do it I'll get back.
