### ISSUE TITLE
Windows AD vs OpenLDAP

### ISSUE THREAD

**Issue by kaysond** [authelia/authelia#380]
Can someone tell me pros/cons of pointing authelia directly to Windows AD vs pointing it to an OpenLDAP server that's either sync'd to AD or forwards authentication to AD?

Not strictly related to authelia, but on the same note, I'm wondering if the answer changes when also considering other services like nextcloud/pure-ftp?

**Comment by rajha-korithrien** [comment]
Under the current Authelia (v3.15), it is difficult to get the underlying Node TLS implementation to accept the self signed certificate that comes with many Windows AD deployments. It works fine with a self signed certificate commonly created for OpenLDAP deployments.

If your LDAP connection requires TLS (ldaps) then I would suggest going the OpenLDAP route with a sync between OpenLDAP and AD. If you don't care about TLS for your ldap traffic, then the difference comes down to the configuration of:

- users_filter
- groups_filter
- group_name_attribute
- mail_attribute

Which will have to be configured correctly to pull information out of the AD schema.

You can not just "forward authentication to AD" because Authelia needs to search through AD/LDAP in order to get group membership information for the user currently authenticating. This can not be determined just by doing a bind operation that is passed from OpenLDAP to AD.

I know nothing about other services, but I hope this answer helps you!

**Comment by kaysond** [comment]
@rajha-korithrien thank you for the answer. Can you elaborate on 

> You can not just "forward authentication to AD" because Authelia needs to search through AD/LDAP in order to get group membership information for the user currently authenticating. This can not be determined just by doing a bind operation that is passed from OpenLDAP to AD.

As far as I know, this should be totally transparent to Authelia. All of the group membership info is directly on OpenLDAP. I can either forward authentication to AD using SASL, or use openldap proxy to use AD's User object information. I think. (I'm just starting to learn about it.)

**Comment by rajha-korithrien** [comment]
@kaysond If you define "forward authentication to AD" as using a proxy, then yes it can be done because group information can be looked up.

If you define it as doing a credential replay/passthrough but the service Authelia is directly talking to can not supply group information, then it will not work.

**Comment by clems4ever** [comment]
@kaysond , have you found a satisfying solution? If not, I advise you to check the latest version of Authelia.
In the meantime I'm closing this issue. Just reopen it or open a new one if you still need help.
