### ISSUE TITLE
Can't use with http, "redirect url isn't safe"

### ISSUE THREAD

**Issue by davidgiga1993** [authelia/authelia#3895]
### Description
I'm currently evaluating authelia with nginx for a lab setup with http, however I've noticed that it's not possible to redirect to a target which uses http.
 
It seems like this behavior is hardcoded [here](https://github.com/authelia/authelia/blob/9c00104cb2f0e56666951d22e31ab5c344de97f2/internal/utils/url.go#L35)

I've got two issues with this line:
1) The method name doesn't imply that it also checks the url scheme. the method does two things which is confusing to a reader
2) It should be possible to allow http traffic, if only for lab/home network purposes

### Expected Behaviour

Non https schemes should be allowed, optionally via a configuration. Additionally this should be mentioned in the docs (or is it and I've overlooked it?)

### Reproduction Steps

Setup authelia with nginx according to the official documentation, try to protect a http endpoint. After the login with authelia the debug message appears in the log and the login UI shows nothing.

### Additional Information

```
authelia  | time="2022-08-26T05:33:35+10:00" level=debug msg="Redirection URL http://nas.home.local/sampleApp is not safe" method=POST path=/api/firstfactor remote_ip=192.168.1.181
```

I'm happy to implement a solution for this if other agree that this should be possible to do/configure

**Comment by james-d-elliott** [comment]
This behavior is not a bug, it's 100% intentional for security. The cookies if transmitted (since they're transmitted via headers) would compromise the session they're attached to. Thus we both have that check, and we set the cookie secure attribute.

What use case is there for this feature?

**Comment by davidgiga1993** [comment]
The use case would just be for easier test setups. Self signed is always an option, but just one more step.
I fully agree that this should never been used without https for any "real" setup.

Also it feels like this should be mentioned in the docs, since it's inconsistent with the login behavior. I mean if http redirects are rejected by design, why can I login to authelia without using https? To be consistent either http should be allowed (via an option) or the whole login page shouldn't work for http.
What are your thoughts on this?

It's also fine by my to leave it like this, however the schema check feels wrong in the referenced method, mostly because it doesn't match the method description/name.

**Comment by james-d-elliott** [comment]
> The use case would just be for easier test setups. Self signed is always an option, but just one more step.
> I fully agree that this should never been used without https for any "real" setup.

I am somewhat hesitant to entertain this as it requires disabling security in a very particular situation that could lead to security issues if we make a critical mistake at a later date or if a user forgets this is set. Hardcoding this has a particular benefit for security in this instance. I will think on it.

> Also it feels like this should be mentioned in the docs, since it's inconsistent with the login behavior.

It is, multiple times. Is there a particular page that you believe it should be noted on that it isn't, or are you suggesting we have it on every page?

> To be consistent either http should be allowed (via an option) or the whole login page shouldn't work for http.
> What are your thoughts on this?

Maybe. I actually agree with this. My only worry is that the moment we do this anyone who has not configured their proxy according to the documentation will have a tantrum about a breaking change.. so it may be something we table for v5.

> It's also fine by my to leave it like this, however the schema check feels wrong in the referenced method, mostly because it doesn't match the method description/name.

Huh?

**Comment by davidgiga1993** [comment]
> It is, multiple times. Is there a particular page that you believe it should be noted on that it isn't, or are you suggesting we have it on every page?

Maybe I have overlooked it then, do you have an example?

I searched through all the [integration pages](https://www.authelia.com/integration/prologue/introduction/) and https is only mentioned in the configuration examples, but there is no sentence explicitly stating that a redirect to a non https page is prohibited. There is one sentence regarding the [secure cookies](https://www.authelia.com/integration/proxies/introduction/#user-identification) only working with https.

A good place for this information would probably be the [Get Started](https://www.authelia.com/integration/prologue/get-started/) page since it's referenced from a lot of other pages


> 
> > It's also fine by my to leave it like this, however the schema check feels wrong in the referenced method, mostly because it doesn't match the method description/name.
> 
What I meant by that is, the method called `URLDomainHasSuffix` does more than its name implies.
When looking through the source code I wasn't expecting this method to also check the scheme. From a clean code perspective it would make more sense either extract the scheme logic into a new method called something like `IsSafeUrl`

**Comment by james-d-elliott** [comment]
> A good place for this information would probably be the [Get Started](https://www.authelia.com/integration/prologue/get-started/) page since it's referenced from a lot of other pages

Yep good idea.

> What I meant by that is, the method called `URLDomainHasSuffix` does more than its name implies.
> When looking through the source code I wasn't expecting this method to also check the scheme. From a clean code perspective it would make more sense either extract the scheme logic into a new method called something like `IsSafeUrl`

This area is not part of our public API, but your point is still valid, we're refactoring this area at present (me specifically) so I'll try to keep this in mind if I've not already done it.

**Comment by jaredmontoya** [comment]
@james-d-elliott I disagree.
`https` is not the only thing that can provide encryption.

Overlay mesh networks like the one I am trying to set up Authelia in can have network-level end to end encryption.
Using https on one is possible but simply useless unless you want traffic to be encrypted twice for no reason.

The unfortunate decision to close this issue in 2022 leaves only two options for me and my setup now:
1: To try and patch Authelia source code myself to remove the check.
2: To forget about using Authelia(and SSO in general) if I need to make significant changes to the codebase to make http work :(

Please reconsider this so I don't have to maintain a patch set and recompile Authelia each time you release an update.

If you find it too scary to let system administrators administrate the system(oh no the horror) then lock unsafe schemas behind some option like `allow_unsafe_schemas` and that will be enough. (I can't imagine someone UNINTENTIONALLY having that on)

**Comment by james-d-elliott** [comment]
The particular requirement in this instance is that traffic between the browser and the edge is encrypted, the traffic between the edge and any other system is entirely up to the administrator. 

The complication with allowing this behavior is not as simple as described. I will write an ADR for this and publish it but the cliff notes are below.

For starters several key elements within Authelia require HTTPS in a way that we cannot control. In particular both OpenID Connect 1.0 and WebAuthn require it, there is no room to not require HTTPS for these services.

Secondly and probably more importantly the lack of HTTPS on the protected resources allows for a direct attack against any instance of this being used to hijack user sessions. The only requirements to performing this becomes misconfiguration where clients are expected to connect to a local resource are resolving to a global IP, or the attacker just needs to adjust name resolution for the user in question, or the network between the client and the application just needs to be mildly compromised. It would also very likely be possible to leverage this attack vector to steal user credentials by having Authelia redirect users to a look-alike page asking the  user to provide their details.

Thirdly this setting would require allowing the session cookies to be presented to servers regardless of if they use TLS transport or not.

Lastly while this is only claimed to affect a person who intentionally opts in, the attack surface of Authelia itself increases. Copied configurations from other users without any understanding about the effect of a configuration setting are abundantly common which should be considered a serious concern for something like this as a user will inevitably configure this without knowing and never know it is an issue. In addition this is a maintenance burden which may unintentionally put every user at risk due to simple mistakes.

---

I will think on this some more while writing the ADR. However chances are we will not add any feature like this, and if we decide to it is basically a certainty the users who decide to use it will not receive any support unless this setting is turned off.

Also realistically no rational argument has been made for why a user would not protect all their applications with transport layer security. Your decision to word your view in the way you did without including a reasonable case where a user would not use TLS is something that you may want to consider in the future as to how it may affect the perspective of others.

ACME has made TLS for the web incredibly accessible, it's completely free and can be done in seconds. In fact most modern proxies support it out of the box, and dated webservers and proxies like nginx can still be configured to use it very easily.

**Comment by james-d-elliott** [comment]
Feel free to open a separate [discussion](https://github.com/authelia/authelia/discussions/new?category=ideas), this is a bug report which again is not a bug.
