### ISSUE TITLE
Do not update activity value for machine generated requests

### ISSUE THREAD

**Issue by bmoe3rd** [authelia/authelia#5271]
### Description

Per rule in activity_control.rules add an option
to NOT update the activity value.

like:
`rules:
    - domain: my.domain
      resources:
      - '^/machine/endpoint$'
      update_activity: false`

update_activity should be true per default.

### Use Case

When continuously updating a website with javascript,
the activity value is updated as well, wich renders the options
- remember_me_duration and
- inactivity
meaningless

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Because inactivity is not considered when a user enables remember me.

**Comment by bmoe3rd** [comment]
> Because inactivity is not considered when a user enables remember me.
Ahh, so the cookie has a expiration date and is replaced on every request !?

I would still request the above Feature for inactivity/expiration!

**Comment by james-d-elliott** [comment]
With remember me checked the expiration becomes whatever the remember me value is, otherwise it's the expiration. Inactivity also only applies to  non-remembered sessions also.

So you have multiple scenarios:

1. You want users to have a hard static expiration regardless, disable remember me and inactivity.
2. You want users to have a inactivity logout and no way to prevent that, you disable remember me and enable inactivity.
3. You want users to have a static expiration but the option to extend it use remember me with inactivity disabled.
4. You want everything enabled.Remember me disables inactivity for users who want it, otherwise they have an inactivity timeout.

All of which the expiration and remember me values can be almost whatever you want.

**Comment by bmoe3rd** [comment]
Thank you for the explanation :+1:

The comments in the configuration file say that expiration is turned off by remember me
wich seems to be the only functional difference between remember me and inactivity to me.

For expiring cookies i would suggest creating a new cookie
with the same expiration date, when update_activity applies to the resource

**Comment by james-d-elliott** [comment]
I don't really agree. Just because it's not exhaustively explained in the config file (which would make the configuration file 10-100 thousand lines if we ever did it), doesn't mean it's not documented clearly. Users should consult the actual documentation for detailed examples, explanations, etc. If this is going to turn into a Q/A I'm going to close it as off topic.


This can probably be implemented best by adding custom policy types. Examples to follow which requires two factor auth but doesn't update the inactivity timer for the `https://example.com/api/status` URL):

```yaml
access_control:
  custom_policies:
    two_factor_no_inactivity:
       enable_two_factor: true
       disable_inactivity: true
  rules:
  - domain: example.com
    policy: two_factor_no_inactivity
    resources: '^/api/status$'
  - domain: example.com
    policy: two_factor
```

**Comment by james-d-elliott** [comment]
This feature is rejected in favor of OAuth 2.0 Bearer Token Usage.
