### ISSUE TITLE
Case insensitive login username

### ISSUE THREAD

**Issue by PoisonFlame** [authelia/authelia#561]
Hi, I have successfully gotten authelia to connect with ldap and see that authelia authentication is case insensitive with respect to the username as  **USER**, is treated differently compared to logging in as **User** even though ldap is using the same entry for both of these logins. 

One thing I noticed that is problematic is 2FA with this scenario. So for example, if I log in as username:joe and set up a 2FA key with Google authenticator. Logout, sign in with username:Joe. I'd have to re-set up 2FA because Authelia treats "joe"  different from "Joe" despite LDAP linking both users to one entry.

I was wondering if this intended, and if so how would I go about making sure that only one 2FA key is used for all users with the same name but different casing.

Thanks

**Comment by james-d-elliott** [comment]
I'm pretty sure this is a bug and should be an easy fix.

**Comment by clems4ever** [comment]
Hello @PoisonFlame , this behavior is expected even though it's not intended. The username is used as the primary key of multiple SQL table that's why the usernames are treated as different users by Authelia.

We should retrieve the username from the LDAP entry instead of using the username provided by the form. The issue is here: https://github.com/authelia/authelia/blob/2e86f270cd0f36a7f1e6a5faf741c0f1b0a08788/internal/handlers/handler_firstfactor.go#L100

I'm gonna fix it.

**Comment by clems4ever** [comment]
I've started checking how to fix that issue but it seems that we'll need to introduce a new key in the LDAP configuration to handle it. So @james-d-elliott and @nightah, I'd like your point of view.

The fix will be done in that function: https://github.com/authelia/authelia/blob/0c43740a4eeba477794b9805dc141047196d6cf2/internal/authentication/ldap_user_provider.go#L187.

Today the username provided as input of this function is the one also stored in the session. The fix would consist in retrieving the username from the search request done in the function and provide it in the UserDetails struct so that the handler can use the retrieved username in the session.

The problem is that we don't know the attribute used as the unique identifier for the user since it's not defined clearly in the current configuration. The only way to know is to check the user filter but it is hardly parsable and the filter could, for any reason, include multiple times the {0} placeholder so I would rather not try to detect the attribute from there. Therefore, what I suggest is to introduce a key called `username_attribute` (no default value to force the user to align this attribute with the filter and avoid discrepancies). 
Then I can retrieve the value for that attribute of the user in the search query so that I can populate UserDetails accordingly and use the right username in the session.

What do you think?

**Comment by james-d-elliott** [comment]
I agree. It might be beneficial to make a pinned issue prior to releasing detailing the fix for the problems people will inevitably encounter if they don't read release notes somehow, then include that with release notes so people can see it easily.

**Comment by nightah** [comment]
> The only way to know is to check the user filter but it is hardly parsable and the filter could, for any reason, include multiple times the {0} placeholder so I would rather not try to detect the attribute from there.

Could you describe an instance where the `{0}` placeholder could be present multiple times?

Pending the above, `username_attribute` is aligned with the rest of the structure so it makes sense.

We could also include examples of commented common attributes both in the documentation and config template:

- Microsoft Active Directory: `sAMAccountName`
- OpenLDAP: `uid`

We also should probably fix up our own suite LDAP schema to conform to RFC-2307 BIS as we also utilise the incorrect field `cn` to store the username.

**Comment by clems4ever** [comment]
@nightah , I meant that we cannot ensure one has not used something like (&(uid={0])(cn={0})).

I will add the documentation as suggested and replace `cn` by uid in the project.
