### ISSUE TITLE
Add support for Argon2 as password hashing function

### ISSUE THREAD

**Issue by csarn** [authelia/authelia#577]
It seems that currently only SHA512 is supported:

> // PasswordHash represents all characteristics of a password hash.
> // Authelia only supports salted SHA512 method, i.e., $6$ mode.

From what I gathered, it seems that using [Argon2](https://en.wikipedia.org/wiki/Argon2), especially in the Argon2id mode, is state-of-the-art. Generally, the SHAxxx family of functions is not a good choice for password hashing. Other alternatives (apart from Argon2) would be bcrypt, scrypt, PBKDF2.

Argon2 is available in go: import "golang.org/x/crypto/argon2".

It would be great for the user to have a choice here, and also a more sensible default hashing function.

**Comment by clems4ever** [comment]
Hello @csarn , SHA512 is indeed not the best function as Argon2 as won the "Password Hashing competition" in 2015. However, it's a decent one given the hash is salted and with a big enough number of rounds. The main problem with SHAXXX family is that a fixed number of rounds involves the same complexity for testing passwords whatever the performance of the machine. So a password which would take years to crack with a given machine could take only few seconds with another machine having higher performance. That is solved with Argon2.
However, as I said previously, a decent number of rounds might still be good enough.

That's being said, I completely agree that we should use the best standards and since it's available in a library, why not use it. I'll have a look at what I can do about it.

Thank you for the report and if you know Go, why not do your first code contribution to the project?

**Comment by csarn** [comment]
Hi @clems4ever, I might actually try to add argon2 myself and create a pull request. I'm relatively new to go, but I already played around a bit with the argon2 library. Should I assign this issue to myself, once I find the time to work on that?

**Comment by clems4ever** [comment]
Sure, I assigned you. Don't hesitate to come discuss in our chatroom if you need some guidance to enter into the code base, I'd be happy to help you out.

**Comment by james-d-elliott** [comment]
@csarn we've added Argon2id in master (see above PR). You should be able to get the changes by using the docker image authelia/authelia:master
