### ISSUE TITLE
Provide self-signed certificate to quickly deploy a test instance of Authelia

### ISSUE THREAD

**Issue by AnalogJ** [authelia/authelia#590]
Hi,
I'm attempting to setup Authelia on my home server and I'm not being correctly redirected to my service after successfully logging in.
I've traced the `Required level for the URL http://droppy.myserver.lan/ is 1` message back to the following lines in the code: https://github.com/authelia/authelia/blob/e6ddedf23de4aa6bb26dc9cf30ec86d6ab6b16b5/internal/handlers/handler_firstfactor.go#L125-L135

Which I then followed to https://github.com/authelia/authelia/blob/3b2d733367c88621e4178301f2bcb4bc03613eee/internal/handlers/safe_redirection.go#L8-L17

It doesn't seem possible to redirect back to non-http urls. Is there a configuration option I'm missing, or am I S.O.L?

**Comment by mattgagliardi** [comment]
Coincidentally...same issue/question here.  TIA!

**Comment by james-d-elliott** [comment]
Hi @AnalogJ and @mattgagliardi. I believe this is intended functionality. I cannot comment on the rational for this, but I suspect it's due to the cookie being sent in every request. This cookie could be theoretically used to bypass any authentication if transmitted over plain-text connections. 

Combining this with reverse proxies and services like Let's Encrypt, it makes a lot of sense. It may help if you have a specific reason/use case you cannot use Let's Encrypt to secure your service, so that we have an intended outcome.

@clems4ever would best be able to answer this question I believe. However I think there may be a way to handle this use case. We could theoretically add a configuration variable to allow insecure redirection, and possibly something else I've been thinking about - an optional feature to lock cookie validity to IP addresses.

**Comment by mattgagliardi** [comment]
@james-d-elliott thanks for clearing up that this is intended, the reasons stated are of course more than valid. FWIW my deployment is in a POC/lab environment...not anything where I'd typically take the time/effort to implement end-to-end encryption, etc.  FWIW I've got little experience (only with CertBot) with Let's Encrypt but my recollection is that it's only workable in publicly-exposed environments (or those than can be temporarily exposed publicly...which this can't).  So it may be off to the land of self-signed certs. for me.

**Comment by james-d-elliott** [comment]
With certbot you can obtain the cert and move/copy it. So if you have one publicly facing (for the certbot request) you can then move it where you want. Additionally lets say you own example.com, and www.example.com points to a publicly facing server, if you also point x.example.com to the same server, in your certbox request if you do "-d example.com -d x.example.com", you will get a cert that covers both domains.

**Comment by mattgagliardi** [comment]
Thanks for the pointer @james-d-elliott, I may give that a run next time.  FWIW I went ahead and just generated a fresh self-signed wildcard for my lab and now I'm rolling along just fine.  Thanks again!

**Comment by clems4ever** [comment]
Hello, this issue has already been raised here: https://github.com/authelia/authelia/issues/408. After second thought, it brings a lot of security concerns that we'll need to take care of if we implement for just avoiding a cert generation in test/development phase.

What I propose is instead to provide a self-signed certificate somewhere so that users don't need to generate one. We could also provide the command to generate one in the documentation.
