### ISSUE TITLE
authelia-v4.38.7-public_html.tar.gz has changed, was this intentional?

### ISSUE THREAD

**Issue by yurivict** [authelia/authelia#7175]
### Version

v4.38.7

### Deployment Method

Other

### Reverse Proxy

Caddy

### Description

This file has changed since the FreeBSD port was updated a few days ago:
```
=> Attempting to fetch https://github.com/authelia/authelia/releases/download/v4.38.7/authelia-v4.38.7-public_html.tar.gz
fetch: https://github.com/authelia/authelia/releases/download/v4.38.7/authelia-v4.38.7-public_html.tar.gz: size mismatch: expected 3687887, actual 3688486
```

Was this intentional, or was the system hacked?

### Reproduction

n/a

### Build Information

```shell
n/a
```

### Logs (Authelia)

```shell
n/a
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
It was re-released due to a build issue.

**Comment by yurivict** [comment]
Ok, thanks.

**Comment by nightah** [comment]
For additional context, we had to manually re-run the build due to an issue with the pre-compiled binaries and how it was reporting the tag on the release.

You can see all builds for [v4.38.7 here](https://buildkite.com/authelia/authelia/builds?branch=v4.38.7).

* [Original Build (with slightly incorrect pre-compiled binaries)](https://buildkite.com/authelia/authelia/builds/28129)
* [New Build (with fixed pre-compiled binaries)](https://buildkite.com/authelia/authelia/builds/28506)
