### ISSUE TITLE
Add support for Contour integration with external auth server using gRPC

### ISSUE THREAD

**Issue by rajivmordani** [authelia/authelia#7402]
### Description

Contour has introduced external auth server capability for envoy. The communication to the external auth server happens over gRPC. Authelia is currently missing support for that integration. 

### Use Case

Use authelia behind contour as the auth server.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Without a clear benefit over the existing envoy external auth server integration this feature is not likely to be implemented.

**Comment by rajivmordani** [comment]
the envoy configuration isn't exposed via Contour. Contour external auth currently only supports gRPC.

**Comment by james-d-elliott** [comment]
It would be trivial for them to support it. Have they been asked and have they rejected it?

**Comment by james-d-elliott** [comment]
I think adding another large dependency like this that we'd have to add to integration testing and also support is unfavorable both due to lack of interest, and the fact the support element for Contour is minimal (solely configuration generation).

Without an official response from them detailing a specific and logical reason they wont support it we're unlikely at this time to invest into something like this.

For these reasons we're closing this but should we add support for enovy gRPC later we'll update this issue accordingly. We'd also welcome an idea to be posted in the discussions section so people can vote on it. We don't refuse features lightly, this was done with careful consideration.

**Comment by james-d-elliott** [comment]
It should be noted that the `status/wont-implement` is to be considered as "wont implement at this time".
