### ISSUE TITLE
Why not store user accounts in SQL database?

### ISSUE THREAD

**Issue by matejdro** [authelia/authelia#826]
Just a question about architecture of the app. 

I'm not sure why do I need to set up separate file storage for user accounts if aurelia is already using SQL database?

This is for small single-server home setup, so LDAP is overkill. But flat file storage also seems redundant when SQL is available.

**Comment by nightah** [comment]
Thanks for your query @matejdro.

The reason users are managed through a file based storage and configuration settings are stored in SQL based storage is purely because a user can modify a flat file with a provided template quite easily.

For a user that is not overly technical even modifying some tables in SQLite might be a little complex.

The overall intent is that as Authelia grows and we implement an admin interface, if local user storage is selected (read: not LDAP) this could be a likely target to migrate into the existing SQL storage.

**Comment by matejdro** [comment]
Thanks for the answer.

**Comment by amanpatel** [comment]
I have a similar question to this.  @nightah  I have an existing website (with apps in it), as a result, I have an existing list of users in a table, and also have a bunch of roles, memberships and other attributes associated with them.

Do you think it would be a good architecture decision on my part to implement a way to sync this to authelia's backend of users? Also the existing users have passwords hashed using a specific type of algorithm. How would authelia know how to verify them?

Does authelia dynamically refresh its user database if I update the file? Is there a way to refresh this if someone on my site registers for a new account, or perhaps even change their password (or name or MFA preferences etc).

Is authelia still a good solution in this scenario? I would rather not go in to implementing LDAP if I don't have to.

**Comment by nightah** [comment]
> Do you think it would be a good architecture decision on my part to implement a way to sync this to authelia's backend of users?

It's possible but I think as Authelia grows it will becoming increasingly difficult to maintain.

> Does authelia dynamically refresh its user database if I update the file? Is there a way to refresh this if someone on my site registers for a new account, or perhaps even change their password (or name or MFA preferences etc).

It does not today.

> Is authelia still a good solution in this scenario? I would rather not go in to implementing LDAP if I don't have to.

I would say that if you don't plan to implement LDAP that an alternative you should explore is OIDC (OpenID Connect)/OAuth2.

**Comment by clems4ever** [comment]
Adding to @nightah's answer, implementing a backend for SQL would probably be feasible indeed but we don't plan to officially support it until we at least have the admin interface where admins can manage their users from. And even then, we would need to analyze the real business need for this because as far as I'm concerned I feel like for home labs, file storage is usually sufficient and users are happy with it and for enterprises, I'm kind of against reinventing the wheel for the moment. Implementing such a connector would be like rewriting what LDAP is made for already, it does not add a lot of value. To me it has a lower priority compared to what we have in our long todo. However, if you implement it on your own, please keep in touch, we might want to use it if we decide to go that way eventually.

File storage does not sync with the filesystem once Authelia has started, however this can be implemented and I'm fine to give a review of this. However, you'd need to take care of the possible race conditions and make sure it won't be possible with your design.

Regarding OIDC, not sure to fully understand the point @nightah . AFAIK, an authorization server is backed by a user database which is usually an LDAP server in enterprise setups. Example with Dex: https://dexidp.io/docs/connectors/ldap/

I hope those insights were useful @amanpatel . Let me know.

**Comment by nightah** [comment]
> Regarding OIDC, not sure to fully understand the point @nightah . AFAIK, an authorization server is backed by a user database which is usually an LDAP server in enterprise setups.

Sorry perhaps I wasn't clear on this point. I meant if they wanted to utilise a public IdP like Google, Microsoft, etc.
That would shift the burden elsewhere, as far as where that leaves all of your existing user data, that's a consideration you'll need to take into account.

**Comment by clems4ever** [comment]
Clearer. Thanks!

**Comment by amanpatel** [comment]
These are very helpful. I think a section like this in the documentation would help out people in my situation:

https://keratin.github.io/authn-server/#/guide-migrating_an_existing_application

I assume something like this is possible to do in Authelia. This is exciting. Thanks for your work on this wonderful project.

**Comment by clems4ever** [comment]
Technically both Authelia and Keratin moves the authentication burden away from many applications so that developers can focus on business logic instead. But they differ on the implementation. Authelia is more about SSO and 2-factor authentication while Keratin seems more about user management. The good thing with Authelia is that the user management side of thing is delegated, meaning administrators can leverage systems which were designed specifically for that use case (LDAP servers).

**Comment by james-d-elliott** [comment]
Related: #1538

I think as long as we provide a sufficiently secure API (disabled unless you configure a secret token, and a strong requirement for the tokens length and content), and/or a CLI for managing the users database we can implement it before a admin UI, just as a beta similar to OIDC where we officially recommend it's not used in production.
