### ISSUE TITLE
BasicAuth restricted to Proxy-Authentication header

### ISSUE THREAD

**Issue by omar-nahhas** [authelia/authelia#841]
There are some cases when the same service is accessed by humans and machines (like Prometheus). Currently, authelia allows the use of basic auth, but it is restricted to basic auth passed through the header [Proxy-Authorization](https://github.com/authelia/authelia/blob/master/internal/handlers/handler_verify.go#L232). 

The problem is that load load balancers consider that header as a [hop by hop header](https://www.freesoft.org/CIE/RFC/2068/143.htm) and is [not passed to the authentication service ](https://github.com/containous/traefik/blob/0b039499c65cf79cd72bd15ade33bbaee2e71d1a/middlewares/auth/forward.go#L56) when set by the originator of the request. 

In my opinion, authelia should allow basic auth using the Authorization header. I know this could expose authelia to a brute-force attack but reverse proxies like Treafic can be [configured](https://github.com/containous/traefik/blob/d7ed42d614fe5ba70b44465f17501bfe112e953f/docs/configuration/backends/kubernetes.md#L355) to strip that header off before passing it to the auth service.

**Comment by clems4ever** [comment]
Hello, @omar-nahhas using Proxy-Authorization was used because I considered Authelia like an authentication proxy meaning two authentications could be encapsulated but beware that Authelia is not a proxy, so it does not forward the header to your backends, the LB does.

Regarding the link that you sent, Proxy-Authorization is not in the list, Proxy-Authenticate is.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authenticate
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization

I'm pretty certain there is a way to configure your loadbalancer to forward/transform the right header to the right backend. I'm pretty sure you can already handle your use case without even using your PR.

However we might still consider your PR for ease of configuration on the LB side if my mates are ok with that. But beware that your problem is likely a configuration problem, not a missing feature in Authelia.

**Comment by james-d-elliott** [comment]
https://tools.ietf.org/html/rfc7235#section-4.4

https://github.com/vulcand/oxy/blob/master/forward/headers.go#L4-L38

Top link is  RFC for the header, second is the implementation of what is considered a Hop header by Traefik. Theoretically all removed from upstream requests. We could test that with whoami.

**Comment by nightah** [comment]
I'm keen to understand this a little bit further, @omar-nahhas could you please elaborate on your specific use-case which does not work with Authelia as it stands?

**Comment by clems4ever** [comment]
Any news @omar-nahhas ?

**Comment by omar-nahhas** [comment]
Thank you for your feedback @clems4ever and @nightah, our use case is simple. We have a set of Prometheus instances behind a set of traefic proxies ( we use Authelia as an authentication server, not as an authentication proxy). We want to protect the Prometheus instances with Authelia for user access, but at the same time, we need to allow Grafana instances (and other federated Prometheus instances) to scrape the protected Prometheus endpoints. 

Currently, there is no apparent way to make this happen, as if we set the `Proxy-Authentication` header on the calling services, it is removed by Traffic with no way to route the header to the request sent to Authelia for authentication. If we set the  `Authentication` proxy, it is ignored by Authelia.

Testing this is relatively easy to do with curl:

To test the sending of `Proxy-Authentication` header:
```curl --proxy-anyauth --proxy-user $USER:$PASSWORD https://prometheus.example.net/```

To test the sending of `Authentication` header:
```curl --user $USER:$PASSWORD https://prometheus.example.net/```

**Comment by nightah** [comment]
Would it not be possible to set a bypass rule for either the IP addresses or subnet (if shared) of your machine based users (Prometheus/Grafana instances)?

Something like this assuming said users are coming from `172.18.0.0/16` which is one of the default Docker networks:
```yaml
    # Rules for machines
    - domain: 'prometheus.example.com'
      networks:
        - 172.18.0.0/16
      policy: bypass
    # Rules for humans
    - domain: 'prometheus.example.com'
      policy: one_factor

**Comment by clems4ever** [comment]
Don't hesitate to join us on Matrix or Gitter @omar-nahhas in order for us to help you solve your issue.
