### ISSUE TITLE
Allow access rules to be defined via labels

### ISSUE THREAD

**Issue by ravensorb** [authelia/authelia#870]
It would be great if access rules could be defined via labels as it would allow for configuration to be consolidated and it would simplify deployment of new applications that use unique FQDNs

Possible example:
```
- authelia.accesscontrol.domain=example.com
- authelia.accesscontrol.policy=one_factor
```

**Comment by clems4ever** [comment]
Hello @ravensorb , thank you for reporting that request.

I'm a bit torn though. As mentioned by @nightah , it means giving the docker socket to Authelia which is a bad idea for security reasons in my opinion because I do not want Authelia to be the relay for a privilege escalation in case of vulnerability. So I agree that this would probably simplify the work of administrators by having all specific configuration in one place but considering the security implication, I'd rather not go in that direction.

Also, using labels is pretty raw and I think it won't be possible to easily replicate the rules ordering used for precedence without introducing some kind of trick with digits in the key. I'm not even talking about multi subjects, multi network, etc... That already seems complex to me at first glance.

Please note that we are also considering moving the ACL part of the configuration (among other things) in an administrative interface, that would not help you but it could complicate our work toward that direction.

All this makes me think about this ticket https://github.com/authelia/authelia/issues/84. It could probably solve your issue in some sense without relying on the docker socket. But I was rather tempted not to address it for the reasons mentioned above: complexity with the expressiveness of ACLs, could make our refactoring task even more complex to introduce the admin interface.

@nightah , @james-d-elliott , what's your feeling about this?

**Comment by nightah** [comment]
Firstly, thanks for utilising Authelia and filing the feature request @ravensorb.

> I'm a bit torn though. As mentioned by @nightah , it means giving the docker socket to Authelia which is a bad idea for security reasons in my opinion because I do not want Authelia to be the relay for a privilege escalation in case of vulnerability.

This can somewhat be addressed by something like [sockguard](https://github.com/buildkite/sockguard).

Having said that, there are more than a few complexities which @clems4ever has highlighted with the ACLs that actually makes this a significant undertaking, with some deeper thought I think it might actually be more effort than it would be worth.

I'm of the opinion that the admin interface is probably the focus area we should be putting effort towards for ACL and general configuration management.

@ravensorb while I understand this is probably not something that you would want to hear, I'm curious to understand whether or not allowing you to easily configure the ACLs within an admin interface is a suitable alternative from your perspective?

**Comment by ravensorb** [comment]
Question -- What about a label that allowed a container specific config file to be leverage as an alternative?  That would allow configurations to be distributed with each container rather than having to update and restart Authelia (this is a bit of a pain point especially for subdomain certs and access control lists).  

@nightah - while an Admin interface is a great feature/enhancement it moves away from one of the key values of containers in that they are designed to be deployed and then thrown away with all configuration being easily defined in an automated way.  Ideally I can stand up an entire env with a single docker-compose (or helm chart) that can be unique from any other env (just need a few certs and domain name changed type of thing).

**Comment by nightah** [comment]
> What about a label that allowed a container specific config file to be leverage as an alternative?

I feel like this is just a poor work-around for what I understand the actual issue you're facing; per the point described below:

> rather than having to update and restart Authelia (this is a bit of a pain point especially for subdomain certs and access control lists).

My expectation would be that when the ACLs are manageable through the Admin interface that you would not require a restart for any added/changed/removed rules. There's obviously a couple other things we need to take into consideration here especially if utilising LDAP, @clems4ever @james-d-elliott I'm thinking of a LDAP cache which refreshes in a defined interval.

> it moves away from one of the key values of containers in that they are designed to be deployed and then thrown away with all configuration being easily defined in an automated way

While this may be somewhat true, we have to take into consideration that Authelia can be used without containers, it can be deployed in multiple ways and realistically the container labels if implemented would only really work for a containerised/k8s deployment.
Plus you would still have to define some of Authelia's configuration and rules within the `config.yml` unless all of Authelia's configuration also moved to be provided via labels or environment variables.

**Comment by james-d-elliott** [comment]
@nightah viper has built in config watching. As long as we're passing configurations to all providers/handlers via pointers we can actually hot reload configuration from disk. 

So theoretically when we implement a mgmt interface for the purpose of changing configuration we can copy the running configuration, make the alterations, and when the admin is ready to save write it to disk. Then Viper will see the changed config and reload the running configuration.

If we wanted additional reliability we could write it to a temporary file, verify the config, then replace the live config file with the temporary file. That way if the configuration somehow gets corrupt in the write process or we have a bug in the UI, it will not cause a crash.

**Comment by clems4ever** [comment]
> While this may be somewhat true, we have to take into consideration that Authelia can be used without containers, it can be deployed in multiple ways and realistically the container labels if implemented would only really work for a containerised/k8s deployment.
> Plus you would still have to define some of Authelia's configuration and rules within the `config.yml` unless all of Authelia's configuration also moved to be provided via labels or environment variables.

I share this point of view.

> @nightah viper has built in config watching. As long as we're passing configurations to all providers/handlers via pointers we can actually hot reload configuration from disk.

Not so simple in my opinion since we'll need to protect access to those rw variables that were read only before. Moreover, some of the configuration was simply transformed before being stored in providers  so it would require a bit of refactoring.

Anyway, I think that in terms of priority, admin interface is definitely the way to go since it will unlock a lot more things in the future. Let's keep the issue open and we'll review that possibility again afterwards and see if there are more upvotes.

**Comment by nightah** [comment]
We're making a conscious decision to not implement this purely because it's for a very specific deployment method and is definitely not trivial to implement.

If things change in future with regards to our concerns around exposing the socket to Authelia and how we would implement ACLs well within labels we will reopen this issue.

**Comment by divStar** [comment]
Just in case... since Authelia would be reading the labels only and not writing them, one could pass the docker.sock as read-only. It's still not great, but having to manually tinker with the `configuration.yml` isn't really the prettiest solution either. Nevertheless it works - so thank you for that and for Authelia :).

**Comment by james-d-elliott** [comment]
Passing the socket as read only has no effect on the access to the socket, this is a common misconception. If you're using this means to "secure" the socket it doesn't work. Any application which can access this socket directly has **_fully unrestrained root equivalent access_** to docker and every container on that instance of docker, and would very likely and very simply be able to perform a complete privilege escalation; which means in effect that a vulnerability in that application could lead to a drastically higher security footprint for that application in that deployment scenario. 

This is not a path we're likely to explore for multiple reasons in addition to this security issue including causing a convoluted expression of rule order especially when you mix labels and a config file, inability to do more than very simple access policies (no way to express most policy items neatly, no way to express denying some users while allowing others unless you default to deny for all apps, no way to express the requirement of higher auth levels for foreign networks vs local ones).

**Comment by divStar** [comment]
Hello @james-d-elliott,

I apologize for even making that comment. I should've looked much more into it. You are absolutely right. Also while there are ways to at least somewhat harden the docker.sock, these ways are somewhat cumbersome and probably not that secure either (at least according to https://doc.traefik.io/traefik/providers/docker/#docker-api-access). So while it's really a pity there isn't a better way to configure the access control rules, it is what it is.

Thank you for taking your time to answer a stupid comment.

**Comment by james-d-elliott** [comment]
No problem at all. I wouldn't consider it stupid. I used to think the same before I was educated by another person.
