### ISSUE TITLE
Redis connection error

### ISSUE THREAD

**Issue by deeztek** [authelia/authelia#992]
Trying the test out authelia following the docs here:

https://docs.authelia.com/deployment/deployment-lite.html

It simply says to modify the configuration.yml and docker-compose.yml with your respective domains and secrets. 

Trying to run authelia and I get the following error:

panic: Redis connection error: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

I would think the default config would have authelia configured withe a default password. What am I missing here. The docs need to be a bit more clear.

**Comment by james-d-elliott** [comment]
I think your issue is the redis provider is configured with a password, but the database isn't, try commenting this line in the config: https://github.com/authelia/authelia/blob/master/compose/lite/configuration.yml#L47

I think this is our error, that shouldn't have been enabled. Apologies if so. If that doesn't fix it please provide your config with anything private redacted.

**Comment by nightah** [comment]
@james-d-elliott is correct, sorry about this, the password line can either be removed entirely or commented and you should be fine.
I'll fix that up now.
